### ISSUE TITLE
Missing timelineReplace for regex

### ISSUE THREAD

**Issue by VanSlanzar** [quisquous/cactbot#1425] opened 2020-05-11 10:09 UTC
After good work @Akurosia on Arr and Heaven, I noticed that this was missing. I'm not talking about missing txt, but (missing timelineReplace for regex). Is this a bug, or like on my last request for missing translations in effect names? Or it's normal, if it's case my apologies. It's only for arr, i have not looked for HW. 
arr zip for all language.
[Arr missing translations.zip](https://github.com/quisquous/cactbot/files/4608902/Arr.missing.translations.zip)

**Comment by Akurosia** [comment] 2020-05-11 11:12
This is in my eyes not a bug and more of an enhancement.
All languages where translations are missing should be flaged with `'missingTranslations': true,` and needs to be translated by members of the community who speak the corresponding language.

Most of all skills, effects and enemy names are translated and usually only the replacementText part is missing as this can have non game related text (nothing you could easly look up in the game files)

Generally it would be good to have someone who could maintain a givin language like i do for the DE part or @mooondark for most of the FR part

**Comment by VanSlanzar** [comment] 2020-05-11 11:24
I was speaking exclusively for this : missing incorrect timelineReplace For regex. #1419 

$ python util/find_missing_translations.py -l fr -f arr
.\ui\raidboss\data\02-arr\raid\t10.js:31 T10 Wild Charge: missing timelineReplace for regex '(?<timestamp>^.{14}) 1b:(?<targetid>[0-9a-f]{8}):(?<target>[^:]*?):....:....:(?<id>001f):'
.\ui\raidboss\data\02-arr\raid\t10.js:55 T10 Prey: missing timelineReplace for regex '(?<timestamp>^.{14}) 1b:(?<targetid>[0-9a-f]{8}):(?<target>[^:]*?):....:....:(?<id>001e):'
.\ui\raidboss\data\02-arr\raid\t12.js:89 T12 Whitefire: missing timelineReplace for regex '(?<timestamp>^.{14}) 1b:(?<targetid>[0-9a-f]{8}):(?<target>[^:]*?):....:....:(?<id>0020):'
.\ui\raidboss\data\02-arr\raid\t12.js:102 T12 Bluefire: missing timelineReplace for regex '(?<timestamp>^.{14}) 1b:(?<targetid>[0-9a-f]{8}):(?<target>[^:]*?):....:....:(?<id>0021):'
.\ui\raidboss\data\02-arr\raid\t13.js:78 T13 Megaflare Share: missing timelineReplace for regex '(?<timestamp>^.{14}) 1b:(?<targetid>[0-9a-f]{8}):(?<target>[^:]*?):....:....:(?<id>0027):'
.\ui\raidboss\data\02-arr\raid\t13.js:91 T13 Earthshaker: missing timelineReplace for regex '(?<timestamp>^.{14}) 1b:(?<targetid>[0-9a-f]{8}):(?<target>[^:]*?):....:....:(?<id>0028):'
.\ui\raidboss\data\02-arr\raid\t6.js:11 T6 Thorn Whip Collect: missing timelineReplace for regex '(?<timestamp>^.{14}) 23:(?<sourceid>[0-9a-f]{8}):(?<source>[^:]*?):(?<targetid>[0-9a-f]{8}):(?<target>[^:]*?):....:....:(?<id>0012):'
.\ui\raidboss\data\02-arr\raid\t6.js:100 T6 Flower: missing timelineReplace for regex '(?<timestamp>^.{14}) 1b:(?<targetid>[0-9a-f]{8}):(?<target>[^:]*?):....:....:(?<id>000d):'
.\ui\raidboss\data\02-arr\raid\t6.js:221 T6 Rotten Stench: missing timelineReplace for regex '(?<timestamp>^.{14}) 1b:(?<targetid>[0-9a-f]{8}):(?<target>[^:]*?):....:....:(?<id>000e):'
.\ui\raidboss\data\02-arr\raid\t7.js:84 T7 Voice: incorrect timelineReplace for regex, got '(?<timestamp>^.{14}) 1a:(?<targetid>[0-9a-f]{8}):(?<target>.*?) gains the effect of (?<effect>voix maudite) from (?<source>.*?) for (?<duration>-?[0-9]+(?:[.,][0-9]+)?(?:e-?[0-9]+)?) seconds\.', needed regexFr '(?<timestamp>^.{14}) 1a:(?<targetid>[0-9a-f]{8}):(?<target>.*?) gains the effect of (?<effect>voix du mal\xe9fice) from (?<source>.*?) for (?<duration>-?[0-9]+(?:[.,][0-9]+)?(?:e-?[0-9]+)?) seconds\.'
.\ui\raidboss\data\02-arr\raid\t7.js:105 T7 Shriek: incorrect timelineReplace for regex, got '(?<timestamp>^.{14}) 1a:(?<targetid>[0-9a-f]{8}):(?<target>.*?) gains the effect of (?<effect>cri maudit) from (?<source>.*?) for (?<duration>-?[0-9]+(?:[.,][0-9]+)?(?:e-?[0-9]+)?) seconds\.', needed regexFr '(?<timestamp>^.{14}) 1a:(?<targetid>[0-9a-f]{8}):(?<target>.*?) gains the effect of (?<effect>cri du mal\xe9fice) from (?<source>.*?) for (?<duration>-?[0-9]+(?:[.,][0-9]+)?(?:e-?[0-9]+)?) seconds\.'
.\ui\raidboss\data\02-arr\raid\t7.js:135 T7 Shriek Reminder: incorrect timelineReplace for regex, got '(?<timestamp>^.{14}) 1a:(?<targetid>[0-9a-f]{8}):(?<target>.*?) gains the effect of (?<effect>cri maudit) from (?<source>.*?) for (?<duration>-?[0-9]+(?:[.,][0-9]+)?(?:e-?[0-9]+)?) seconds\.', needed regexFr '(?<timestamp>^.{14}) 1a:(?<targetid>[0-9a-f]{8}):(?<target>.*?) gains the effect of (?<effect>cri du mal\xe9fice) from (?<source>.*?) for (?<duration>-?[0-9]+(?:[.,][0-9]+)?(?:e-?[0-9]+)?) seconds\.'
.\ui\raidboss\data\02-arr\raid\t8.js:11 T8 Stack: missing timelineReplace for regex '(?<timestamp>^.{14}) 1b:(?<targetid>[0-9a-f]{8}):(?<target>[^:]*?):....:....:(?<id>0011):'
.\ui\raidboss\data\02-arr\raid\t9.js:90 T9 Meteor: missing timelineReplace for regex '(?<timestamp>^.{14}) 1b:(?<targetid>[0-9a-f]{8}):(?<target>[^:]*?):....:....:(?<id>000[7a9]):'
.\ui\raidboss\data\02-arr\raid\t9.js:98 T9 Meteor Stream: missing timelineReplace for regex '(?<timestamp>^.{14}) 1b:(?<targetid>[0-9a-f]{8}):(?<target>[^:]*?):....:....:(?<id>0008):'
.\ui\raidboss\data\02-arr\raid\t9.js:106 T9 Stack: missing timelineReplace for regex '(?<timestamp>^.{14}) 1b:(?<targetid>[0-9a-f]{8}):(?<target>[^:]*?):....:....:(?<id>000f):'
.\ui\raidboss\data\02-arr\raid\t9.js:400 T9 Dragon Marker: missing timelineReplace for regex '(?<timestamp>^.{14}) 1b:(?<targetid>[0-9a-f]{8}):(?<target>[^:]*?):....:....:(?<id>0014):'

**Comment by Akurosia** [comment] 2020-05-11 11:34
Most of them are incorrect handeled "1b:" entries where there is a capture group (wiht capture: false its working fine) and needs to be fixed in the script itself and is not a missing translation.

T6 Thorn Whip Collect is the same but with "23:"

point 10, 11 and 12 are FR related once where i would need help to get the correct translation

**Comment by VanSlanzar** [comment] 2020-05-11 11:47
10,11, 12 are still a problem related to French, arf... this language ^^.
Cast on boss is Voix maudite, Cri maudit
Debuff on player is Voix du maléfice, Cri du maléfice
https://www.garlandtools.org/db/#status/452

**Comment by Akurosia** [comment] 2020-05-11 11:55
10, 11, 12 are than just a incorrect order of apply as it tries first replace parts from replaceSync and than ~effectnames. Translations are already in file and this is just a bug of the find_translation script

1b does not contain any language specific content and should be handeled by timeline.js i think

**Comment by VanSlanzar** [comment] 2020-05-11 14:56
I'm sorry, I'm not at all competent in these areas, but if you need translations, I will help you with the resolution of this issue.

**Comment by VanSlanzar** [comment] 2020-05-12 15:45
can this issue be closed? I saw  a request made  to correct this.

**Comment by VanSlanzar** [comment] 2020-05-18 13:01
Thank you for the update on the search tool to correct most of the errors listed. Only (10, 11, 12) are still detected. is this correctable? Because it works well, as mentioned above this is just a bug of the find_translation script.

**Comment by Akurosia** [comment] 2020-05-18 13:16
could you do a test run for one of them to see if it is just the test which failes and not the regex itself?

**Comment by VanSlanzar** [comment] 2020-05-18 14:10
I entered the instance, and I killed the boss to see the mechanics. Everything works well. Only the test fails, as you mentioned above.

**Comment by quisquous** [comment] 2020-05-21 01:13
One way to "fix" this is to switch to NetRegexes for this, where you can use an `effectId` instead of `effect` name.  And then you won't need the colliding effect name.

**Closed** 2020-05-26 15:45 UTC
Labels: bug
