### ISSUE TITLE
hibiyasleep (and OverlayPlugin in general?) no longer supported?

### ISSUE THREAD

**Issue by amackenzie** [quisquous/cactbot#553] opened 2019-08-19 15:32 UTC
It seems like according to https://github.com/hibiyasleep/OverlayPlugin/issues/37 that OverlayPlugin in general isn't going to be updated or anything going forward, will this be an issue for Cactbot? It looks like there haven't been any changes for years as it is.

**Comment by markuznw** [comment] 2019-08-19 18:31
There is @ngld picking it up for what I know, his modified version works much better than the original for me despite still being in beta phase. The problem is cactbot (and other plugins) aren't yet compatible by default.

There was pull #442 to make it compatible but it got reverted due to issues. I hope they can figure it out and make it compatible with both versions :)

**Comment by quisquous** [comment] 2019-08-20 06:35
There's not really anything to worry about here.  Either I'll support the OverlayPlugin myself if something breaks or I'll move to ngld's version.  I'm still planning on moving to ngld's version, but haven't sorted out all the issues yet.

**Comment by ngld** [comment] 2019-08-20 21:04
FWIW, I've done most of the porting work already (https://github.com/ngld/cactbot/tree/feature/eventSource). It's not completely done, yet (pulltimer doesn't work).
I'm planning on doing some more testing and eventually make it backwards compatible with the old OverlayPlugin though that might be a PITA. Not sure, yet.

Oh, as an added bonus, Cactbot works over WebSocket with my OverlayPlugin so you can put it in OBS if you want to.

**Comment by sajid-ahmad** [comment] 2019-08-21 11:10
What's OBS?

**Comment by tant4lus** [comment] 2019-08-21 17:45
OBS is Open Broadcaster Software.  It's one of the many programs you can use to stream your gameplay to Twitch.

**Closed** 2019-08-25 16:32 UTC
