### ISSUE TITLE
Jobs: BrowserConsole: /deep/ combinator is deprecated. 

### ISSUE THREAD

**Issue by CptDraco** [quisquous/cactbot#25] opened 2018-01-10 13:21 UTC
Getting 2 errors I can't work around yet. Posting here for future reference. I know one issue is ACT related and likely nothing to be done.

**Jobs: BrowserConsole: /deep/ combinator is deprecated.** 

**Failed to clear temp storage: It was determined that certain files are unsafe for access within a Web application, or that too many calls are being made on file resources. SecurityError**

**Comment by hibiyasleep** [comment] 2018-02-27 02:06
This sometimes appears when you open developer tools, not a bug of cactbot. and it's totally safe to ignore.

**Comment by quisquous** [comment] 2018-02-27 03:13
I agree that this is benign, and I was unable to find any way around to not get this error.  I'm going to close this as WontFix.

**Closed by quisquous** 2018-02-27 03:13 UTC
Labels: bug
