### ISSUE TITLE
T9 - Problems

### ISSUE THREAD

**Issue by DCRSakio** [quisquous/cactbot#3296] opened 2021-07-13 09:15 UTC
In T9 (Nael van Darnus)
At the Ice/Fire/Lightning Dragon-Phase the RaidAlert goes crazy as heall and displays the whole code (and with TTS even speaks it for severeal minutes).

I'm using German Overlay/Callouts

**Comment by valarnin** [comment] 2021-07-13 15:58
Does this issue reproduce in raidemulator? Can you upload a network log file for the fight?

**Comment by panicstevenson** [comment] 2021-07-13 20:13
Running this through raidemulator, I get:
```
{id: "T9 Dragon Marks", netRegex: /^(?:20)\|(?:[^|]*)\|(?:[^|]*)\|(?:Nael Deus Darnus)\|(?:7E6)\|/i, netRegexDe: /^(?:20)\|(?:[^|]*)\|(?:[^|]*)\|(?:Nael Deus Darnus)\|(?:7E6)\|/i, netRegexFr: /^(?:20)\|(?:[^|]*)\|(?:[^|]*)\|(?:Nael Deus Darnus)\|(?:7E6)\|/i, netRegexJa: /^(?:20)\|(?:[^|]*)\|(?:[^|]*)\|(?:ネール・デウス・ダーナス)\|(?:7E6)\|/i, …} TypeError: Cannot read property '0' of undefined
    at infoText (t9.js:343)
    at Object.valueOrFunction (popup-text.ts:993)
    at PopupTextAnalysis._addTextFor (popup-text.ts:1327)
    at PopupTextAnalysis._onTriggerInternalInfoText (popup-text.ts:1190)
    at triggerPostPromise (popup-text.ts:920)
    at triggerPostDelay (popup-text.ts:952)
    at PopupTextAnalysis.OnTriggerInternal (popup-text.ts:959)
    at PopupTextAnalysis.OnTrigger (PopupTextAnalysis.ts:105)
    at PopupTextAnalysis.onEmulatorLog (PopupTextAnalysis.ts:159)
    at async AnalyzedEncounter.analyzeFor (AnalyzedEncounter.ts:216)
```

```js
    {
      id: 'T9 Dragon Marks',
      netRegex: NetRegexes.startsUsing({ id: '7E6', source: 'Nael Deus Darnus', capture: false }),
      netRegexDe: NetRegexes.startsUsing({ id: '7E6', source: 'Nael Deus Darnus', capture: false }),
      netRegexFr: NetRegexes.startsUsing({ id: '7E6', source: 'Nael Deus Darnus', capture: false }),
      netRegexJa: NetRegexes.startsUsing({ id: '7E6', source: 'ネール・デウス・ダーナス', capture: false }),
      netRegexCn: NetRegexes.startsUsing({ id: '7E6', source: '奈尔·神·达纳斯', capture: false }),
      netRegexKo: NetRegexes.startsUsing({ id: '7E6', source: '넬 데우스 다르누스', capture: false }),
      durationSeconds: 12,
      infoText: (data, _matches, output) => output.marks({
        dir1: output[data.naelMarks[0]](),
        dir2: output[data.naelMarks[1]](),
      }),
      outputStrings: {
        ...diveDirections,
        marks: {
          en: 'Marks: ${dir1}, ${dir2}',
          de: 'Markierungen : ${dir1}, ${dir2}',
          fr: 'Marques : ${dir1}, ${dir2}',
          ja: 'マーカー: ${dir1}, ${dir2}',
          cn: '标记： ${dir1}, ${dir2}',
          ko: '카탈징: ${dir1}, ${dir2}',
        },
      },
    },
    ```

**Comment by valarnin** [comment] 2021-07-13 20:35
It's probably something in the collector trigger `'T9 Final Phase Reset'`, but I don't have any T9 logs to run through to debug.

**Comment by panicstevenson** [comment] 2021-07-14 00:59
I believe this is fixed by https://github.com/quisquous/cactbot/pull/3297, but that's just a guess since I don't have a fire in log myself.

**Comment by quisquous** [comment] 2021-09-26 16:58
I'm going to mark this fixed.  Please reopen if it's still happening.

**Closed by quisquous** 2021-09-26 16:58 UTC
