### ISSUE TITLE
Raidboss; UWU Garuda timeline doesn't show.

### ISSUE THREAD

**Issue by NotMikaa** [quisquous/cactbot#1904] opened 2020-10-23 04:40 UTC
## Description
Garuda log rarely starts in UWU First pull i get a timeline, anything after that for garuda no longer shows.

## Additional information
Please let me know where i can find logs etc to help further.

**Comment by quisquous** [comment] 2020-10-24 17:58
Thanks for filing an issue about this.  A bunch of questions for you:

* If you open up `ui\raidboss\data\04-sb\ultimate\ultima_weapon_ultimate.txt` and add the line: `0.0 "--Reset--" sync / 21:........:40000010:/ window 10000 jump 0` to the top, does it start resetting properly?
* I am a bit surprised that this has broken.  Did this used to work but then suddenly stop working with a particular cactbot version?
* Does the timeline start when you get to Ifrit?
* What language are you playing in?
* Would you mind zipping up and attaching a [https://github.com/quisquous/cactbot/blob/main/docs/FAQ-Troubleshooting.md#how-to-find-a-network-log](Network log) here?

One other thing that would be worth doing would be to turn on [debug mode](https://github.com/quisquous/cactbot/blob/main/docs/CactbotCustomization.md#check-if-your-file-is-loaded) for raidboss.  When you do that, it will add a time next to your timeline, and if the timeline is running, then it will keep counting up.  It would be good to know when this bug happens if the timeline has stopped or if the timeline is still running.

**Comment by NotMikaa** [comment] 2020-10-25 16:43
Thanks for your reply,

I threw it above `0 "--Reset--" sync /Removing combatant The Ultima Weapon\.  Max HP: \d{8}\./ window 10000 jump 0`
I'll test this shortly to see if it resets.

This used to work before an earlier revision. I'd like to say 19.4? maybe from memory.
The time line works flawlessly from Ifrit every time.

I play in English.

I dont have any old logs at the moment but if the issue persists i'll upload a log tomorrow after rad.

**Comment by NotMikaa** [comment] 2020-10-26 01:08
Update: It looks the sync fixed it!

**Comment by quisquous** [comment] 2020-10-26 05:12
Excellent.  Thanks for testing!

**Comment by gamescom15** [comment] 2020-11-18 08:19
Wanted to point out that this hasn't fixed the issue for me. I'll try to see if the timeline appears on garuda with 0.20.0 on the next raid day, but i doubt it.

**Comment by gamescom15** [comment] 2020-11-24 23:22
Tested it out and the garuda timeline never appears, not even on the first pull.

Oddly enough, i got it to appear once after a wipe where i started act late in the pull.
It does not really matter to me as we don't rely on cactbot anywhere, but i'd just like to confirm that the bug sadly isn't fixed^^

**Comment by NotMikaa** [comment] 2020-11-25 03:48
> 
> 
> Tested it out and the garuda timeline never appears, not even on the first pull.
> 
> Oddly enough, i got it to appear once after a wipe where i started act late in the pull.
> It does not really matter to me as we don't rely on cactbot anywhere, but i'd just like to confirm that the bug sadly isn't fixed^^

Hi, this is what fixed it with me, how ever it needed to be applied every update.

this is the first 10 lines of the text file.

\plugins\Cactbot\ui\raidboss\data\04-sb\ultimate\ultima_weapon_ultimate.txt

`# Ultima Weapon Ultimate
## http://clees.me/guides/uwu/

hideall "--sync--"
hideall "--Reset--"

0 "--Reset--" sync / 21:........:40000010:/ window 10000 jump 0
0 "--Reset--" sync /Removing combatant The Ultima Weapon\.  Max HP: \d{8}\./ window 10000 jump 0

### Phase 1: Garuda ###`

Can you try that and see if that fixes it for you.

**Comment by MaikoTan** [comment] 2020-11-25 04:15
You can use \`\`\` and \`\`\` to wrap the code block so it would show normally.

just like

```
\`\`\`
[code block]
\`\`\`
```

```
[code block]
```

**Comment by quisquous** [comment] 2020-11-28 19:08
@gamescom15 Looking at the timeline file, this is almost certainly because you have `Hide Chat Log (for privacy)` checked in your FFXIV settings in ACT.  Does teleporting to Summerford Farms and starting a `/countdown 5` work for you?

**Comment by quisquous** [comment] 2020-12-06 20:26
@gamescom15 Did that end up being the issue?

**Comment by gamescom15** [comment] 2020-12-06 20:36
Yes, unchecking „hide chat log“ made the Garuda timeline appear from the start.
Thanks for the help, I would have never guessed that that was the cause of the error.

**Comment by quisquous** [comment] 2020-12-06 20:55
Thanks for the bug report!

**Closed by quisquous** 2020-12-06 20:55 UTC
Labels: bug
