### ISSUE TITLE
Ucob Timelines

### ISSUE THREAD

**Issue by lollirenzo** [quisquous/cactbot#1474] opened 2020-06-11 09:43 UTC
Been in Ucob for a couple days now, i noticed that timelines for Twintania phase and Nael phase are pretty much messed up due to dps push, it doesn't count skipped mechanics and goes on with normal timeline even if the party skips mechanics.

**Comment by quisquous** [comment] 2020-06-11 16:12
This is a duplicate of #1394.  Can you attach a network log there?

**Closed by quisquous** 2020-06-11 16:12 UTC
Labels: bug
