### ISSUE TITLE
npm generate-log-guide is timezone dependent

### ISSUE THREAD

**Issue by quisquous** [quisquous/cactbot#3389] opened 2021-08-14 02:33 UTC
If I run this script, I get a bunch of incorrect updates like:
```diff
 ACT Log Line Examples:
-[14:13:16.276] 26:10FF0001:Tini Poutini:46504615:75407:75407:10000:10000:24:0:-645.238:-802.7854:8:1.091302:1500:3C:0:0A016D:41F00000:E0000000:1E016C:41F00000:E0000000::c1b3e1d63f03a265ffa85f1517c1501e
-[14:13:16.276] 26:10FF0001::46504621:49890:49890:10000:10000:24:0:::::1500:3C:0::f62dbda5c947fa4c11b63c90c6ee4cd9
-[14:13:44.502] 26:10FF0002:Potato Chippy:46504621:52418:52418:10000:10000:32:0:99.93127:113.8475:-1.862645E09:3.141593:200F:20:0:0A016D:41F00000:E0000000:1E016C:41F00000:E0000000:0345:41E8D4FC:10FF0001:0347:80000000:10FF0002::d57fd29c6c4856c091557968667da39d
+[11:13:16.276] 26:10FF0001:Tini Poutini:46504615:75407:75407:10000:10000:24:0:-645.238:-802.7854:8:1.091302:1500:3C:0:0A016D:41F00000:E0000000:1E016C:41F00000:E0000000::c1b3e1d63f03a265ffa85f1517c1501e
+[11:13:16.276] 26:10FF0001::46504621:49890:49890:10000:10000:24:0:::::1500:3C:0::f62dbda5c947fa4c11b63c90c6ee4cd9
+[11:13:44.502] 26:10FF0002:Potato Chippy:46504621:52418:52418:10000:10000:32:0:99.93127:113.8475:-1.862645E09:3.141593:200F:20:0:0A016D:41F00000:E0000000:1E016C:41F00000:E0000000:0345:41E8D4FC:10FF0001:0347:80000000:10FF0002::d57fd29c6c4856c091557968667da39d
```

I think the script could fix the timezone in place so that everybody gets consistent output.  Alternatively everybody can move leftward a few (or more) timezones.

**Comment by valarnin** [comment] 2021-08-17 17:01
I'd like to renew my petition that the entire globe just changes to UTC timezone.

(I'll look into this)

**Comment by valarnin** [comment] 2021-08-17 18:53
Various options to fix this:

1. Update logic in EmulatorCommon to always use UTC for timezone conversion, fix a bunch of other things impacted by this (mostly around discrepancies between network log timestamp and non-network log timestamps in emulator for timeline purposes)
2. Update to latest node 16, to pick up this commit, and then set the appropriate env var: https://github.com/nodejs/node/commit/c0deeeacb2cedf0194ac8f1a8f3a66c502870ca5
3. Set the env var anyways, and it'll only be fixed in non-windows environments
4. Split the example network line out, convert the timestamp to UTC, recreate the network line, then use that version for both the network example and the ACT line example
5. Replace the generated ACT line's timestamp to match the expected value from network line

**Comment by MaikoTan** [comment] 2021-08-19 02:04
Is it make sense to just add an options to EmulatorCommon says `utc?: boolean` or `timezone?: string`, default to current timezone if not specified?

**Comment by valarnin** [comment] 2021-08-19 02:07
The problem is that it's called from LineEvent's prefix function, which is called from the constructor, which is called from ParseLine. So that utc variable would have to be passed all the way through somehow.

**Comment by quisquous** [comment] 2021-08-19 02:50
I think the environment variable option is the least appealing to me.  If you're going to do that, you might as well have a static variable on EmulatorCommon.  That would at least be a little bit more obvious and explicit about what's going on.

I think always using UTC for time zone conversion makes some sense to me? It seems like if there are issues between network log timestamp and act log line timestamp, then they would already be an issue even before this, if you were using a log that was written by somebody in another timezone.

Is there a different option you'd prefer?

**Comment by valarnin** [comment] 2021-08-19 03:21
The reason there would be an issue here is because when emulator passes the log lines to popup text or timeline, it uses the original raw network line for that part, but the converted line for the game log part. If the raw network line says 4pm PDT, and the converted line says `16:00:00`, that's fine. If the network line says `4pm PDT` and the converted line says `23:00:00`, that's not going to be right.

And you're right that this is a problem if you're using a network log created in a different timezone, the impact is really limited though since built-in triggers all use network lines and timelines all use converted lines. If there's ever a mix, it's going to break things with timeline.

Option 4 seems to be the least-impactful fix but it won't fix the underlying problem when some time down the road conversion of timeline stuff to network format starts happening.

Option 1 could be done in base LineEvent but it'd require bumping the version of the encounter so it would get re-parsed on load. There's also a question of how to handle displaying in emulator, should we display UTC, or display in local timezone?

**Closed** 2021-08-30 03:36 UTC
Labels: bug
