### ISSUE TITLE
alarmText text is used as a tts text and block sound file usage

### ISSUE THREAD

**Issue by Vayhyr** [quisquous/cactbot#180] opened 2018-07-01 17:40 UTC
I made a small custom trigger for when I die.
![xwuva7b 1](https://user-images.githubusercontent.com/32498169/42137057-0a56cb24-7d66-11e8-8fb8-555c4e63e61f.png)
But recently, the alarmText text is used as a tts text, so the sound file is not playing.
Removing the alarmText make sound file playing correctly.

**Comment by blazenz1** [comment] 2018-07-01 22:20
infoText texts are also being read by tts for some reason

**Comment by quisquous** [comment] 2018-07-01 22:31
This does not seem to happen for me locally.  What do you have set in **cactbot/user/raidboss.js**?

**Comment by Vayhyr** [comment] 2018-07-01 22:53
raidboss.js : https://gist.github.com/9d2dafa8d676277f2f972647f2eb8cb2

**Comment by quisquous** [comment] 2018-07-02 04:04
Thanks.  I'll try to take a look at that tomorrow and see if I can repro using that.  I suspect I broke something when I simplified how to specify tts.

**Comment by quisquous** [comment] 2018-07-06 17:47
Thanks, @Vayhyr.

Sorry for taking so long to get back to this, but I tried a couple of different approaches and I couldn't find anything that would solve all the edge cases.  I think I'm going to need to leave cactbot in this state.  The problem is this: currently the (global and per trigger) options for tts overrides options for sounds in all cases.  So if you want tts you can set speech=true sound=false.  If you want sound, you can set speech=false sound=true.  If you want silence, you can set speech=false sound=false.  For triggers that do play sounds like yours, if I defaulted to sound overriding tts, there'd be no way to set options to make such a trigger play tts if you wanted it.

You have a couple of options:
(1) Add an id to your trigger, and then add something in `Options.PerTriggerOptions` for that trigger id to set `SpeechAlert` to false.  See: https://github.com/quisquous/cactbot/blob/master/user/raidboss-example.js#L201.
(2) I just added 8eed2b8, which would allow you to add `tts: false` to your "you died" trigger, and this will prevent default tts from playing.  You can use this locally now by grabbing https://github.com/quisquous/cactbot/archive/master.zip and updating your **cactbot/ui/** folder with the **ui/** folder in there.  This will be in the next release.

@blazenz1: Are you having something similar going on? Which triggers are playing with tts that you don't want them to be? What is your **cactbot/user/raidboss.js**?

**Closed** 2018-07-11 18:38 UTC
