### ISSUE TITLE
Confusing stuff :( Not sure if its working or not ;/

### ISSUE THREAD

**Issue by Dark-Majin** [quisquous/cactbot#638] opened 2019-09-30 01:10 UTC
1.does your act otherwise work fine? yes
2.Does your parser work? yes
3.Did you have the overlayplugin? yes with kagerou
4.did you start act as administrator? yes
Client is in german.
I have also Hojoring 7.7 and Discordtrigger installed.
Well the testdummy did not trigger at all , most of the lvl 60 raid / trials i tried did nothing as well.
Afterwards i went into e2s and strangly it spoke and worked pretty well.
The Twinning had maybe 2-3 triggers but in english. And e1n worked pretty poorly as well.

I'm kind of newbie in this stuff. So any ideas how to start troubleshooting or are most of the triggers just not working in german ?

mfg Majin

**Comment by JLGarber** [comment] 2019-09-30 02:37
As far as I know, Kagerou isn't officially supported by Cactbot. Very possibly that's wrong, but you may have to use the base RainbowMage overlay that was maintained by Hibiyasleep until recently. (ngld is working on an update to that overlay for modernization purposes.) That would be the first thing to try.

One other thing to look for is to see whether there are any errors in the log. Plugins > Overlayplugin.dll, then look at the window at the bottom. If you see anything marked in red, see whether that might have a hint. The Twinning has full German support, so the fact that it's not working indicates that there's something very wrong with your setup. (I did a lot of the English work on the Twinning, Quisquous made some changes to my work, and then Akurosia did the German translations. You can see this in the [file history](https://github.com/quisquous/cactbot/commits/master/ui/raidboss/data/05-shb/dungeon/twinning.js). You might see whether that all looks correct.)

**Comment by quisquous** [comment] 2019-09-30 04:34
Translations are sort of done ad hoc by whoever contributes them.  So, support can be sort of spotty, sometimes.  In general, the savage raids get translated, but everything else not necessarily.  e2n doesn't have any german translations, but I would expect e2s to work properly.

It looks like the twinning doesn't have enough translations for the timeline to start (as they're all zone closing messages that have to be translated).  It is very surprising to me that things called out in English, however.  This suggests to me that cactbot is running in English (as there are some triggers that don't need translations) and most triggers need translations and so don't call out.  Can you check what's in your overlay plugin log? It should print out something like `[9/29/2019 9:34:07 PM] Info: Language: de`

I'm sorry that there's not better documentation about the state that everything is in.

**Comment by Dark-Majin** [comment] 2019-09-30 11:14
yeah cactbot detect german.
And it has no red marks while running.
At the twinning there was basically only call outs at the first boss for the the jump attack thats it.

**Comment by Akurosia** [comment] 2019-09-30 13:06
Savage should work mostly (i am also using German client).
Some updates for savage are comming in the next few hours as i am currently adding all missing translations i can find.

for twinning the only missing things should be following 2 lines, rest should be translated correctly:

0 "--Reset--" sync /00:0839:.*is no longer sealed/ window 100000 jump 0 #MISSINGSYNC
1167.3 "Gravity/Crossray??" #MISSINGTEXT

**Comment by Dark-Majin** [comment] 2019-09-30 13:21
Akurosia can u start a test at the dummies ?

**Comment by Akurosia** [comment] 2019-09-30 13:23
dummy has no german regex for provoke so it can not work.
if you type "/e You use Provoke" it should work fine if you are in Middle La Noscea

**Comment by Dark-Majin** [comment] 2019-09-30 13:32
/e You use Provoke does nothing ;/

**Comment by Akurosia** [comment] 2019-09-30 13:35
ok the provoke example might not work as you did not renamed your raidboss-example.js to raidboss.js
After this you need to reload your timeline overlay

**Comment by Dark-Majin** [comment] 2019-09-30 16:23
i have no raidboss-example.js at all oO

**Comment by Akurosia** [comment] 2019-09-30 16:54
it is under Overlayplugin -> cactbot -> user

**Comment by Dark-Majin** [comment] 2019-09-30 18:51
ok it gives me a provoke notice . thats sth ;D

**Comment by Akurosia** [comment] 2019-09-30 18:55
Other things like, poke, bow etc are currently not working in german (i already made a PR which will make them work)

**Comment by Akurosia** [comment] 2019-10-01 16:24
Only @quisquous knows when a new release will be comming.
In the mean time you could clone the repo or download the master and replace the ui/raidboss content

**Comment by Dark-Majin** [comment] 2019-10-02 17:22
ok the master ones works way better now ty ;)
Btw i noticed a difference depending on the class i m playing ..
Is there an option to make a genereal line for discord callouts ?

**Comment by Akurosia** [comment] 2019-10-02 17:37
The difference is normal as some triggers are designed for healer/tank only (some things e..g are only displayed if they target you and not others)
and i don't think there is a generall discord callout option on cactbot side but this should be confirmed by @quisquous

**Comment by quisquous** [comment] 2019-10-03 05:44
Yeah, I usually only do a release when there's a been a lot of changes.  I might do one more before 5.1, but also maybe no.

I'm not quite sure what you mean by general discord callout.

**Comment by Dark-Majin** [comment] 2019-10-04 17:32
well i think before the new masterupdates the boss told more stuff.
Now its personalized .. This means the bot stops speaking if i m dead or he skips tankbusters / aoe which even as dd is not bad to know for burst phases

**Comment by Akurosia** [comment] 2019-10-04 17:36
which boss exactly do you mean? twinning?
Also since you hadn't the user/raidboss.js available, try renaming it and see if the issue still happens.
Otherwise i would need more information on what is missing for you and what did you expect

**Comment by Dark-Majin** [comment] 2019-10-04 17:36
no e2s

**Comment by Akurosia** [comment] 2019-10-04 19:10
if you need further assistance, we need more information what is not really working for you.
I just ran a check agains the raidboss emulator and everything got called out like expected for me (as i am playing DD, i did not checked for healer/tank specific callouts)

**Comment by Dark-Majin** [comment] 2019-10-04 21:16
Well i m not sure its not working ...
Some people mentioned call outs stops if i m dead.
And i thought a general line which include tankbuster/ aoe would be not wrong if u wish so.
I can work pretty well with the bot as it is right now

**Comment by quisquous** [comment] 2019-10-05 22:12
Callouts always happen whether you're alive or dead.  There are callouts for aoe and tankbusters, and those are role specific.  I think dps cooldown alignment is generally not related to either of those things, and so is just noise.

**Comment by quisquous** [comment] 2019-10-27 19:09
Is this still a problem for you? I'm not sure I understand what's going on here.

**Comment by Dark-Majin** [comment] 2019-10-27 23:23
No not really .. i suppose everything works as intended :)
Keep up the great work

**Closed** 2019-10-28 00:31 UTC
