### ISSUE TITLE
Stop showing gen_log_guide translations when using findTranslations

### ISSUE THREAD

**Issue by Akurosia** [quisquous/cactbot#3398] opened 2021-08-16 17:06 UTC
when using `npm run util -- findTranslations "-l=de" "-f=ui"` following missing translations are displayed that dont really make sense to translate:
```
F:\Github\cactbot_aku2\util\gen_log_guide.ts:58 "examples: {"
F:\Github\cactbot_aku2\util\gen_log_guide.ts:74 "examples: {"
F:\Github\cactbot_aku2\util\gen_log_guide.ts:82 "examples: {"
F:\Github\cactbot_aku2\util\gen_log_guide.ts:94 "examples: {"
F:\Github\cactbot_aku2\util\gen_log_guide.ts:110 "examples: {"
F:\Github\cactbot_aku2\util\gen_log_guide.ts:118 "examples: {"
F:\Github\cactbot_aku2\util\gen_log_guide.ts:130 "examples: {"
F:\Github\cactbot_aku2\util\gen_log_guide.ts:143 "examples: {"
F:\Github\cactbot_aku2\util\gen_log_guide.ts:158 "examples: {"
F:\Github\cactbot_aku2\util\gen_log_guide.ts:169 "examples: {"
F:\Github\cactbot_aku2\util\gen_log_guide.ts:178 "examples: {"
F:\Github\cactbot_aku2\util\gen_log_guide.ts:191 "examples: {"
F:\Github\cactbot_aku2\util\gen_log_guide.ts:205 "examples: {"
F:\Github\cactbot_aku2\util\gen_log_guide.ts:218 "examples: {"
F:\Github\cactbot_aku2\util\gen_log_guide.ts:226 "examples: {"
F:\Github\cactbot_aku2\util\gen_log_guide.ts:234 "examples: {"
F:\Github\cactbot_aku2\util\gen_log_guide.ts:246 "examples: {"
F:\Github\cactbot_aku2\util\gen_log_guide.ts:255 "examples: {"
F:\Github\cactbot_aku2\util\gen_log_guide.ts:267 "examples: {"
F:\Github\cactbot_aku2\util\gen_log_guide.ts:281 "examples: {"
F:\Github\cactbot_aku2\util\gen_log_guide.ts:293 "examples: {"
F:\Github\cactbot_aku2\util\gen_log_guide.ts:302 "examples: {"
F:\Github\cactbot_aku2\util\gen_log_guide.ts:316 "examples: {"
F:\Github\cactbot_aku2\util\gen_log_guide.ts:325 "examples: {"
F:\Github\cactbot_aku2\util\gen_log_guide.ts:337 "examples: {"
F:\Github\cactbot_aku2\util\gen_log_guide.ts:356 "const mappedLogLines: LocaleObject<LineDocTypes[]> = {"
```

**Comment by MaikoTan** [comment] 2021-08-16 17:51
`-f=ui/` add a little slash might get rid of it.
Technically those examples are translatable strings so this should not be a bug but intended?

**Comment by Akurosia** [comment] 2021-08-17 05:45
Please ignore the /ui part.
I would not expect it to show at all since for 99% it would be the exact same lines (only some ACT logline would have langugae specific text i think)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by valarnin** [comment] 2021-08-17 16:59
I think it should be fine to leave this as-is and set keys to `undefined` if they're intentionally left to default to `en`, e.g.:

```ts
    examples: {
      en: [
        '00|2021-04-26T14:12:30.0000000-04:00|0839||You change to warrior.|d8c450105ea12854e26eb687579564df',
        '00|2021-04-26T16:57:41.0000000-04:00|0840||You can now summon the antelope stag mount.|caa3526e9f127887766e9211e87e0e8f',
        '00|2021-04-26T14:17:11.0000000-04:00|0b3a||You defeat the embodiment.|ef3b7b7f1e980f2c08e903edd51c70c7',
        '00|2021-04-26T14:12:30.0000000-04:00|302b||The gravity node uses Forked Lightning.|45d50c5f5322adf787db2bd00d85493d',
        '00|2021-04-26T14:12:30.0000000-04:00|322a||The attack misses.|f9f57724eb396a6a94232e9159175e8c',
        '00|2021-07-05T18:01:21.0000000-04:00|0044|Tsukuyomi|Oh...it\'s going to be a long night.|1a81d186fd4d19255f2e01a1694c7607',
      ],
      de: undefined,
      fr: undefined,
      ja: undefined,
      cn: [
        '00|2021-06-17T21:00:15.0000000+08:00|0039||背景音乐的静音状态已解除。|be868045474b2467df1ffcfc29123217',
      ],
      ko: undefined,
    },
```

I've confirmed that this prevents the missing translations from firing.

**Comment by quisquous** [comment] 2022-04-09 19:18
The keys here have changed to locales (e.g. `en-US`) and so no longer show up.  I'll close this issue.

**Closed by quisquous** 2022-04-09 19:18 UTC
Labels: bug
