### ISSUE TITLE
add a formatter

### ISSUE THREAD

**Issue by Trim21** [quisquous/cactbot#3191] opened 2021-06-26 12:57 UTC
Many contributors have different IDE and different IDE settings.

for example, some part of [this file](https://github.com/quisquous/cactbot/blob/main/types/trigger.d.ts) is indented with 4 space, but some part is indented with 2 space.

I think we do need a formatter to format all files to unify the code style.

I have to say I spend twice more time removing the diff caused by indent than real content writing when creating that PR contains this file.

just find that prettier has a [require-pragma](https://prettier.io/docs/en/options.html#require-pragma) options which could make it progressively

prettier even has a [range](https://prettier.io/docs/en/options.html#range) option...

**Comment by panicstevenson** [comment] 2021-06-26 16:58
Going to continue the conversation that seems to be happening in a few places here:

@quisquous' [comment from 3193](https://github.com/quisquous/cactbot/pull/3193#issuecomment-869028463):

> Saying again what @panicstevenson said in 3102 (comment), I have a lot of reservations about prettier. I really don't like what it inconsistently does to quotes and there's no way to configure that. We also parse a lot of JavaScript with code and so we'd need to fix up a bunch of things to handle inconsistent quotes.
> 
> I want to take a look at clang-format as an option first, because that's one thing I haven't explored before making a choice about what formatter to use.

Then there's a bit of a thread from 3190; important bits:

Trim21:

> (and indent and formatting problems are driving me crazy, why some part of this file is indented with 4 spaces? we should just add prettier with typescript......)

panicstevenson:

> I think the issue here is that we don't have @typescript-estlint/indent, so things like types, interfaces, etc. don't have their indentation enforced. Enabling the rule and running it, there were 396 problems currently in the codebase.
> ...
> EDIT: Nevermind, it impacts eslint/indent, and doesn't support the same options, so that's probably a non-starter.

quisquous:

> How do you feel about 3164?

I noticed there's a comment in #3164:

`// The indent rule does a poor job with TypeScript type declarations, so disable.`, which feels like the main issue? Could we either solve that ourselves, or see what we can do with a formatter? I'm not really super opposed to a formatter + ESLint sprinkled on top, but I just haven't found anything suitable.

**Comment by quisquous** [comment] 2021-06-26 17:02
> // The indent rule does a poor job with TypeScript type declarations, so disable.,

Interfaces are fine, it's just type type lines (or union/intersection) that are so big that they extend onto the next line that it doesn't know what to do with.  (You mentioned this weird indenting in your other post that I was responding to.)  I think this not super common.  There were only like ~3 places where I noticed this.  I think that PR moooostly gets the job done.

**Comment by quisquous** [comment] 2021-06-26 17:05
Re: closing https://github.com/quisquous/cactbot/pull/3193#issuecomment-869030224.

It's possible prettier is the best option, but I would like to try clang-format out as one final option before choosing prettier or choosing not to use a formatter.

**Comment by Trim21** [comment] 2021-06-26 17:07
> I think that PR moooostly gets the job done.

Not really I think...


```diff
diff --git a/types/trigger.d.ts b/types/trigger.d.ts
index 32ecde8f..ed91e7b2 100644
--- a/types/trigger.d.ts
+++ b/types/trigger.d.ts
@@ -9,8 +9,8 @@ import { CactbotBaseRegExp, TriggerTypes } from './net_trigger';
 // that use matches from any number of Regex or NetRegex functions.
 export type TargetedParams = 'sourceId' | 'source' | 'targetId' | 'target';
 export type TargetedMatches = NetMatches['StartsUsing'] | NetMatches['Ability'] |
-    NetMatches['GainsEffect'] | NetMatches['LosesEffect'] | NetMatches['Tether'] |
-    NetMatches['WasDefeated'] | NetMatches['None'];
+  NetMatches['GainsEffect'] | NetMatches['LosesEffect'] | NetMatches['Tether'] |
+  NetMatches['WasDefeated'] | NetMatches['None'];
```

let's say, both passed eslint of that PR.

**Comment by panicstevenson** [comment] 2021-06-26 17:07
> > // The indent rule does a poor job with TypeScript type declarations, so disable.,
> 
> Interfaces are fine, it's just type type lines (or union/intersection) that are so big that they extend onto the next line that it doesn't know what to do with. (You mentioned this weird indenting in your other post that I was responding to.) I think this not super common. There were only like ~3 places where I noticed this. I think that PR moooostly gets the job done.

Right, I understand where you're coming from, but the reason we're discussing this is (if I'm understanding Trim's concern correctly) because those types are 'randomly' spaced; for example:

```ts
export type TriggerSet<Data extends RaidbossData> = {
                                      // ZoneId.MatchAll (aka null) is not supported in array form.
                                      zoneId: ZoneId | number[];
                                      resetWhenOutOfCombat?: boolean;
                                      overrideTimelineFile?: boolean;
                                      timelineFile?: string;
                                      timeline?: TimelineFunc;
                                      triggers?: NetRegexTrigger<Data>[];
                                      timelineTriggers?: TimelineTrigger<Data>[];
                                      timelineReplace?: TimelineReplacement[];
                                      timelineStyles?: TimelineStyle[];
                                      initData?: DataInitializeFunc<Data>;
}
```
Runs with no complaints.

**Comment by Trim21** [comment] 2021-06-26 17:07
even this pass:

```TS
export type TargetedMatches = NetMatches['StartsUsing'] | NetMatches['Ability'] |
    NetMatches['GainsEffect'] | NetMatches['LosesEffect'] | NetMatches['Tether'] |
  NetMatches['WasDefeated'] | NetMatches['None'];
```

**Comment by panicstevenson** [comment] 2021-06-26 17:08
> It's possible prettier is the best option, but I would like to try clang-format

I will try to get this up and running right now and see what I can find

**Comment by quisquous** [comment] 2021-06-26 17:08
> Interfaces are fine, it's just type type lines (or union/intersection) that are so big that they extend onto the next line that it doesn't know what to do with. 

As I said.  I'm not saying it's perfect.  I'm saying those lines are uncommon and that PR is at least an improvement?

**Comment by Trim21** [comment] 2021-06-26 17:12
clang-format looks fine `npx clang-format --glob=webpack/**/*.ts -i --style=Google`

just need to find out how to disable import sorting

**Comment by panicstevenson** [comment] 2021-06-26 17:16
Here's basically the only diff for TEA, for reference:
```diff
@@ -53,14 +57,14 @@ const nisiToString = (nisiNum, output) => {
   // nisiNum is 0-3
   // assume output is using nisiTypes.
   switch (nisiNum) {
-  case 0:
-    return output.blueAlpha();
-  case 1:
-    return output.orangeBeta();
-  case 2:
-    return output.purpleGamma();
-  case 3:
-    return output.greenDelta();
+    case 0:
+      return output.blueAlpha();
+    case 1:
+      return output.orangeBeta();
+    case 2:
+      return output.purpleGamma();
+    case 3:
+      return output.greenDelta();
   }
 };

@@ -224,33 +228,33 @@ const nisiPassOutputStrings = {
 // Convenience function called for third and fourth nisi passes.
 const namedNisiPass = (data, output) => {
   // error?
-  if (!(data.me in data.finalNisiMap))
-    return output.unknown();
+  if (!(data.me in data.finalNisiMap)) return output.unknown();

   if (data.me in data.nisiMap) {
     // If you have nisi, you need to pass it to the person who has that final
     // and who doesn't have nisi.
     const myNisi = data.nisiMap[data.me];
     let names = Object.keys(data.finalNisiMap);
-    names = names.filter((x) => data.finalNisiMap[x] === myNisi && x !== data.me);
+    names =
+        names.filter((x) => data.finalNisiMap[x] === myNisi && x !== data.me);

     let namesWithoutNisi = names.filter((x) => !(x in data.nisiMap));

     // If somehow it's the case that you've had SUCH a late pass that there
     // isn't anybody without without nisi, at least use the names of folks who
     // have the final debuff.
-    if (namesWithoutNisi.length === 0)
-      namesWithoutNisi = names;
+    if (namesWithoutNisi.length === 0) namesWithoutNisi = names;

     // If somehow still there's nobody, give a message so that it's not silent
     // but you're probably in trouble.
     if (namesWithoutNisi.length === 0)
-      return output.passNisi({ type: nisiToString(myNisi, output) });
+      return output.passNisi({type: nisiToString(myNisi, output)});

     // The common case.  Hopefully there's only one person in the names list,
     // but you never know.
     const players = namesWithoutNisi.map((x) => data.ShortName(x)).join(', ');
-    return output.passNisiTo({ type: nisiToString(myNisi, output), players: players });
+    return output.passNisiTo(
+        {type: nisiToString(myNisi, output), players: players});
   }

   // If you don't have nisi, then you need to go get it from a person who does.
@@ -258,7 +262,7 @@ const namedNisiPass = (data, output) => {
   let names = Object.keys(data.nisiMap);
   names = names.filter((x) => data.nisiMap[x] === myNisi);
   if (names.length === 0)
-    return output.getNisi({ type: nisiToString(myNisi, output) });
+    return output.getNisi({type: nisiToString(myNisi, output)});

   return output.getNisiFrom({
     type: nisiToString(myNisi, output),
```

**Comment by panicstevenson** [comment] 2021-06-26 17:18
It looks like it also has a somewhat rough time on type declarations too though :(
```ts
export type NetRegexTrigger<Data extends RaidbossData> =
    TriggerTypes extends infer T ?
    T extends TriggerTypes ? (BaseTrigger<Data, T>&PartialNetRegexTrigger<T>) :
                             never :
    never;

export type GeneralNetRegexTrigger<Data extends RaidbossData,
                                                T extends TriggerTypes> =
    BaseTrigger<Data, T>&PartialNetRegexTrigger<T>;
```

**Comment by panicstevenson** [comment] 2021-06-26 17:33
The issue I've found that maybe @Trim21 has ideas for is that clang-format wants to be installed globally and ran; I don't know about running npx with husky since that would be making the package call (I'm assuming it checks the cache) every time for every file.

**Comment by Trim21** [comment] 2021-06-26 18:14
clang-format works fine with JS, not TS

```TS
export type Params<T extends string> =
  Partial < Record<Exclude<T, 'timestamp'|'capture'>, string|string[]>&{
  timestamp: string;
  capture: boolean;
}
> ;
```

**Comment by panicstevenson** [comment] 2021-06-26 18:18
> clang-format works fine with JS, not TS

That's unfortunate; I _think_ we could do what [prettier-eslint](https://www.npmjs.com/package/prettier-eslint) does and run [tsfmt](https://github.com/vvakame/typescript-formatter) then `eslint --fix`. `tsfmt` puts a couple things into the wrong place, but overall looks like it does the right thing, and then can be nudged back into the right place with `eslint`; I'd have to test it a little more.

**Comment by Trim21** [comment] 2021-06-26 19:10
Yes, just write a simple script, run prettier, then run eslint.

**Comment by quisquous** [comment] 2021-06-26 21:22
> clang-format works fine with JS, not TS

It seems like clang-format just has opinions that I disagree with about typescript unions and intersections.

```diff
-type PlayerChangedRet = Job extends infer T ? T extends Job ?
-  PlayerChangedJobDetails<T> & PlayerChangedBase : never : never;
+type PlayerChangedRet = Job extends infer T ?
+    T extends Job ? PlayerChangedJobDetails<T>&PlayerChangedBase : never :
+    never;
```

or

```diff
   'BRD': {
-    songName: 'Ballad' | 'Paeon' | 'Minuet' | 'None';
-    songMilliseconds: number;
-    songProcs: number;
+    songName: 'Ballad'|'Paeon'|'Minuet'|'None'; songMilliseconds: number; songProcs: number;
     soulGauge: number;
   };
```

It's possible this is [working as intended](https://github.com/angular/clang-format/issues/38#issuecomment-247925830) (thanks to Panic who pointed this out to me).

Otherwise, the output seems pretty reasonable to me, but that one point seems really unfortunate and makes me not want to use clang-format.

**Comment by quisquous** [comment] 2021-07-01 03:42
I think #3212 is looking ready.  It's roughly as fast as the existing eslint (maybe a little slower) but does a lot of things I like.  I think more of its options agree with what we're already doing.  The other nice thing is that it fits into eslint, and so vscode can also tell you when things are not formatted.

**Closed** 2021-08-01 05:06 UTC
Labels: enhancement
