### ISSUE TITLE
2019-02-27 12:22:26 AM: Info: raidboss: BrowserConsole: Uncaught TypeError: Cannot read property 'OnLogEvent' of undefined (Source: file:///C:/Users/jerroOverlayPlugin/cactbot/ui/raidb/Dktop/Actor_v2.0.4.2/ACT/plugin/oss/raidboss.html, Line: 47)es

### ISSUE THREAD

**Issue by femtoubik** [quisquous/cactbot#371] opened 2019-02-27 06:23 UTC

**Comment by quisquous** [comment] 2019-02-27 06:26
I think this is a duplicate of #298.  If you restart ACT or reload the plugin, it should likely fix it.

**Comment by femtoubik** [comment] 2019-02-27 22:15
![image](https://user-images.githubusercontent.com/47796536/53526818-cd9d4c00-3aaa-11e9-9665-f90755f91b23.png)
sadly not fixed

**Comment by Akurosia** [comment] 2019-03-10 10:54
Since release 0.9.3 i get these messages all the time.
Restart, new installation etc does not fix this.
<img width="1141" alt="Advanced_Combat_Tracker_2019-03-10_11-49-15" src="https://user-images.githubusercontent.com/7465469/54083975-34ccc300-432b-11e9-8716-5b6a1a3878a7.png">

**Comment by quisquous** [comment] 2019-03-10 22:24
Are these messages continuous? Does the plugin stop working, or is it just a few error messages on startup?

**Comment by Akurosia** [comment] 2019-03-11 14:57
Yes they are continuous.
Plugin is still working.

I just made a screenshot where i could see all 4 types.

**Comment by Akurosia** [comment] 2019-03-11 16:17
Small reminder since i am not sure if op also playes with german client:
I play with a german client and this had produced some issues in the past

**Comment by femtoubik** [comment] 2019-03-11 16:26
English client

**Comment by quisquous** [comment] 2019-10-27 19:12
I think using the ngld overlay should address these startup issues.  Let me know if that doesn't fix it.

**Closed by quisquous** 2019-10-27 19:12 UTC
Labels: bug
