### ISSUE TITLE
Party member UI replacement

### ISSUE THREAD

**Issue by haasn** [quisquous/cactbot#578] opened 2019-08-26 00:32 UTC
I'm starting to use cactbot's overlays more and more as a replacement for this game's dysfunctional mess of a default UI, but one of the most obvious missing aspects of it is the entire party frame.

My ideal UI would be as close of a faithful reproduction to [Grid2](https://www.curseforge.com/wow/addons/grid2) as we could accomplish. I'll probably eventually start work on something like this (maybe also with interactivity like clicking on party members to select them ingame, via the use of hotkeys like F1-F8).

In either case, this would require the cactbot plugin know information about party members and expose this to the overlays. To perhaps avoid repeating work: Have you ever worked on this at all? Do you have any plans to?

**Comment by quisquous** [comment] 2019-08-26 06:25
I would love to expose party information to cactbot.  There's a number of things that could use it: raidboss needs to know who all the party members are for triggers, oopsy could tell you when friendly aoe abilities missed somebody, etc.  It should all be exposed in C# via the FFXIV_ACT_Plugin.DataSubscription.PartyListChanged event handler, and getting that info from the ffxiv plugin itself seems like the right approach.

This may be my own C# ignorance, but I haven't figured out how to access that properly.  I can find the ffxiv plugin via the list of plugins (like I do for language), but I can't cast to the FFXIV_ACT_Plugin.FFXIV_ACT_Plugin type for the reasons that are listed in the comment in the get language function.  And I can't use `dynamic` either, as you can't `+=` to an eventhandler on a dynamic object.  Maybe you have to use reflection?  It's not clear to me.

At any rate, I would love to have party member information (names, worlds, number of party members, and then periodic updates on hp/mp/status/whatever) exposed to cactbot.

**Comment by haasn** [comment] 2019-08-26 12:07
You can safely downcast using the [`as` operator](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/type-testing-and-cast). (And, incidentally, also safely test for presence of the ACT Plugin using the `is` operator, rather than going by assembly name)

e.g.:

```csharp
var ffxiv_plugin = plugin.pluginObj as FFXIV_ACT_Plugin.FFXIV_ACT_Plugin;
ffxiv_plugin.DataSubscription.PartyListChanged += delegate (System.Collections.ObjectModel.ReadOnlyCollection<uint> partyList, int partySize)
{
    foreach (var u in partyList)
        logger_.LogInfo("party list changed: {0}", u);
};
```

**Comment by haasn** [comment] 2019-08-26 12:20
Incidentally, even just straight up casting works. I'm not sure why exactly the comment is trying to say casting doesn't work, but it works in my testing.

**Comment by haasn** [comment] 2019-08-26 15:33
Also, this is not strictly relevant to this particular issue, but we might also want to work on replacements for the target, focus target, target of target etc. frames.

**Comment by ngld** [comment] 2019-08-26 18:43
Was the assembly loading issue caused by the fact that Cactbot is loaded through OverlayPlugin and not ACT?
I haven't had problems with casting [myself](https://github.com/ngld/OverlayPlugin/blob/master/OverlayPlugin.Core/FFXIVRepository.cs) but I might read the `DataRepository` through reflection instead because it seems more robust (it'll survive changes to the FFXIV plugin as long as that property exists).

**Comment by quisquous** [comment] 2019-08-31 18:28
Neither of these work for me.  Because the FFXIV_ACT_Plugin has been loaded by ACT from a file, it isn't the same FFXIV_ACT_Plugin that is being referenced by ACT when building.  Using `is` does not work, because these types are not the same.

It seems like this issue: https://blogs.msdn.microsoft.com/aszego/2009/10/16/avoid-using-assembly-loadfrom/

1) using as
```
diff --git a/CactbotOverlay/FFXIVPlugin.cs b/CactbotOverlay/FFXIVPlugin.cs
index 0271375..941493c 100644
--- a/CactbotOverlay/FFXIVPlugin.cs
+++ b/CactbotOverlay/FFXIVPlugin.cs
@@ -58,7 +58,7 @@ namespace Cactbot {
         // Cannot "just" cast to FFXIV_ACT_Plugin.FFXIV_ACT_Plugin here, because
         // ACT uses LoadFrom which places the assembly into its own loading
         // context.  Use dynamic here to make this choice at runtime.
-        dynamic plugin_derived = ffxiv_plugin;
+        FFXIV_ACT_Plugin.FFXIV_ACT_Plugin plugin_derived = ffxiv_plugin as FFXIV_ACT_Plugin.FFXIV_ACT_Plugin;
         return (int)plugin_derived.DataRepository.GetSelectedLanguageID();
       } catch (Exception e) {
         logger_.LogError("Error while determining language: {0}", e.ToString());
```

`8/31/2019 11:23:17 AM: Error: raidbossy: Error while determining language: System.NullReferenceException: Object reference not set to an instance of an object.
   at Cactbot.FFXIVPlugin.GetLanguageId()`

2) casting directly
```
diff --git a/CactbotOverlay/FFXIVPlugin.cs b/CactbotOverlay/FFXIVPlugin.cs
index 0271375..91382aa 100644
--- a/CactbotOverlay/FFXIVPlugin.cs
+++ b/CactbotOverlay/FFXIVPlugin.cs
@@ -58,7 +58,7 @@ namespace Cactbot {
         // Cannot "just" cast to FFXIV_ACT_Plugin.FFXIV_ACT_Plugin here, because
         // ACT uses LoadFrom which places the assembly into its own loading
         // context.  Use dynamic here to make this choice at runtime.
-        dynamic plugin_derived = ffxiv_plugin;
+        FFXIV_ACT_Plugin.FFXIV_ACT_Plugin plugin_derived = (FFXIV_ACT_Plugin.FFXIV_ACT_Plugin)ffxiv_plugin;
         return (int)plugin_derived.DataRepository.GetSelectedLanguageID();
       } catch (Exception e) {
         logger_.LogError("Error while determining language: {0}", e.ToString());
```

`8/31/2019 11:25:30 AM: Error: raidbossy: Error while determining language: System.InvalidCastException: [A]FFXIV_ACT_Plugin.FFXIV_ACT_Plugin cannot be cast to [B]FFXIV_ACT_Plugin.FFXIV_ACT_Plugin. Type A originates from 'FFXIV_ACT_Plugin, Version=2.0.2.9, Culture=neutral, PublicKeyToken=null' in the context 'LoadNeither' in a byte array. Type B originates from 'FFXIV_ACT_Plugin, Version=2.0.2.9, Culture=neutral, PublicKeyToken=null' in the context 'Default' at location 'C:\Program Files (x86)\Advanced Combat Tracker\FFXIV_ACT_Plugin.dll'.
   at Cactbot.FFXIVPlugin.GetLanguageId()`

**Comment by ngld** [comment] 2019-09-03 13:12
The context is different because ACT uses `Assembly.Load` and OverlayPlugin loads addons with `Assembly.LoadFrom`. I see two possible solutions to this:

1. Load Cactbot as an ACT plugin (like #577 does).
2. Modify OverlayPlugin to load addons the same way ACT does.

**Comment by haasn** [comment] 2019-09-03 15:30
Oh. It might work for me because I use [a fork of OverlayPlugin](https://github.com/ezsoftware/OverlayPlugin)

That being said, I didn't see any commits in that branch that would differentiate the way assembly loading is performed.

**Comment by quisquous** [comment] 2019-09-08 00:45
@ngld Your pull request does not fix this for me.  If I make the same changes I listed above in https://github.com/quisquous/cactbot/issues/578#issuecomment-526855007, then I get the same errors.

I wonder if there's something wrong in my setup somehow? Why does this work for everybody else and not me?

**Comment by quisquous** [comment] 2021-06-05 22:07
It is now possible to get party information from OverlayPlugin.  Unfortunately, there's no party ordering so a UI couldn't be built on top of the party list itself.  I am not planning on implementing such an overlay myself and it doesn't necessarily have to be one built inside of cactbot.  I think I am going to close this feature request for now.

**Closed by quisquous** 2021-06-05 22:07 UTC
Labels: enhancement
