### ISSUE TITLE
Browser TTS stop working again

### ISSUE THREAD

**Issue by ellenpozzi** [quisquous/cactbot#2858] opened 2021-05-14 05:06 UTC
Since yesterday, browser TTS function doesn't work so I have to uncheck the "use browser text to speech option" to use the windows default voice (which I hate it!).

**Comment by quisquous** [comment] 2021-05-19 01:52
This is a duplicate of #2860, so I will close this issue and follow up there.

**Closed by quisquous** 2021-05-19 01:52 UTC
