### ISSUE TITLE
Raid Emulator

### ISSUE THREAD

**Issue by Stijntj** [quisquous/cactbot#792] opened 2019-11-23 14:05 UTC
As soon as I add the raid emulator I get this error. 
(I also don't exactly know how to work with it, but I followed instructions and loaded a log file but nothing changes in the emulator)

[23/11/2019 15:01:44] Error: JS Handler call failed: Newtonsoft.Json.JsonReaderException: Error reading JObject from JsonReader. Current JsonReader item is not an object: String. Path '', line 1, position 22.
   bij Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   bij Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
   bij RainbowMage.OverlayPlugin.OverlayApi.<>c__DisplayClass16_0.<callHandler>b__0()

It's no a pressing issue. 
Thanks in advance, Max

**Comment by Legends0** [comment] 2019-11-24 21:23
I get this error too, but I can get it working with the hibaya version of the OverlayPlugin. The new regex functions do not work though.

**Comment by Ikuni17** [comment] 2019-11-29 22:03
I started having this issue with cactbot `0.13.0.0` and ngld OverlayPlugin `0.11.2.0` after I had it working for a couple days. Realized I had to have FFXIV running while using the emulator. The error will still show but everything was working fine after I imported the log.

**Comment by quisquous** [comment] 2020-03-21 20:00
Belatedly, I think this is a duplicate of #853.  The fact that the raid emulator uses local storage (which has worse limits) can cause errors on longer fights or when storing multiple fights.

**Closed by quisquous** 2020-03-21 20:00 UTC
Labels: bug
