### ISSUE TITLE
Cactbot overlay too small with ngld Overlay

### ISSUE THREAD

**Issue by NielsH** [quisquous/cactbot#788] opened 2019-11-21 18:22 UTC
Hello,

I recently reconfigured ACT to use the ngld Overlay with Cactbot. Everything works OK, except for one thing:
When I start up ACT the Cactbot overlay is too small on my monitor. To give some context.
- I use 3 monitors. 2x 1920x1200 and 1x 3840x2160 on which I play FFXIV.

The Cactbot overlay appears to render incorrectly, perhaps it misjudges the resolution. Dragging it to increase the size instantly snaps it back to the correct render-size. After this it will persist for a while, even after closing-reopening ACT, but the next day it will be broken again and I need to do the same thing.

To illustrate I made a video to show what I mean:
https://streamable.com/52pnd

**Comment by quisquous** [comment] 2019-11-23 06:55
Do you have a custom Zoom set in the overlay, and that's what makes the size bigger, but it's just ignoring that until you resize it? (Just making sure I understand.) I couldn't see the Zoom setting in your video.

**Comment by NielsH** [comment] 2019-11-23 11:09
I don't think I have a custom zoom set in; I've been looking through the options and cannot find the option to change the zoom.

Another piece of information: I noticed the Kagerou DPS Meter overlay also is a bit wonky; often it goes "missing" when starting ACT and I don't see it on any monitor. When clicking "Reset overlay position" I can see it again and drag it to the correct position.

Since not just Cactbot is having an issue I guess it may be more related to ngld overlayplugin itself? Perhaps it is better to report it there, what do you think?

**Comment by ngld** [comment] 2019-11-23 14:15
This looks like a duplicate of ngld/OverlayPlugin#13. TL;DR: ACT doesn't support Windows' scaling or "high DPI" feature. As a result Windows does the scaling itself and does a terrible job.
The easiest way to fix the issue is to open ACT's compatibility options and set the scaling mode to `Application`. This turns off the scaling and thus gets rid of the glitches but it obviously doesn't scale anymore.
@quisquous The zoom slider hasn't been released, yet. I have to fix a few issues with the new curl downloader (or revert it) before I can push another update.

The best solution I could figure out so far would be to render the overlays in a separate subprocess which could then do the scaling itself but that adds additional IPC overhead and makes the whole thing more complicated. I'll eventually implement that due to other issues with CEF in the ACT process but it's going to take quite some time to finish.

**Comment by NielsH** [comment] 2019-11-23 22:05
Hi,

Thanks for the response. This seems to work for Kagerou DPS meter; it now always shows up. The text within ACT is a bit wonky, see screenshot:
![image](https://user-images.githubusercontent.com/848114/69485888-7d8ac480-0e45-11ea-80f5-4f1c34fc2fa8.png)

However, this is only the ACT problem and as such not so bad.

However, the cacbot overlay is permanently "small" this way and even if I drag it it won't increase the size anymore sadly :( Perhaps the zoom-slider will help out once it is released.

**Comment by NielsH** [comment] 2019-12-01 16:01
It seems that with version 0.11.2.0 the issue is fixed! I didn't touch the zoom level at all, so not sure what caused it to be fixed now... ?

**Comment by quisquous** [comment] 2019-12-12 16:52
Glad to hear this seems fixed.

**Closed by quisquous** 2019-12-12 16:52 UTC
Labels: bug
