### ISSUE TITLE
Bug: ESLint doesn't run properly in VSCode

### ISSUE THREAD

**Issue by MaikoTan** [quisquous/cactbot#2719] opened 2021-04-13 13:28 UTC
## Desctiption

After #2567 landed, when I am using VSCode opening up cactbot repo, ESLint didn't work always.

When I look at `Output` window and select `ESLint`, then I saw the error stack looks like:
<details>
<summary>Error of ESLint (Click to expand)</summary>
<pre><code>
(node:36347) UnhandledPromiseRejectionWarning: /workspaces/cactbot-workspace/cactbot/eslint/cactbot-output-strings.js:107
          stack.triggerID = node.parent.parent.properties.find((prop) => prop.key && prop.key.name === 'id')?.value?.value;
                                                                                                             ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:1053:16)
    at Module._compile (internal/modules/cjs/loader.js:1101:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at /workspaces/cactbot-workspace/cactbot/node_modules/eslint-plugin-rulesdir/index.js:30:103
    at Array.reduce (<anonymous>)
    at Object.get rules [as rules] (/workspaces/cactbot-workspace/cactbot/node_modules/eslint-plugin-rulesdir/index.js:30:10)
(node:36347) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:36347) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:36347) UnhandledPromiseRejectionWarning: /workspaces/cactbot-workspace/cactbot/eslint/cactbot-output-strings.js:107
          stack.triggerID = node.parent.parent.properties.find((prop) => prop.key && prop.key.name === 'id')?.value?.value;
                                                                                                             ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:1053:16)
    at Module._compile (internal/modules/cjs/loader.js:1101:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at /workspaces/cactbot-workspace/cactbot/node_modules/eslint-plugin-rulesdir/index.js:30:103
    at Array.reduce (<anonymous>)
    at Object.get rules [as rules] (/workspaces/cactbot-workspace/cactbot/node_modules/eslint-plugin-rulesdir/index.js:30:10)
(node:36347) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
</code></pre>
</details>

**So it turns out that ESLint (or nodejs, precisely) didn't know the new syntax of ES2020.**
**Then I found that ESLint in VSCode was called by the VSCode built-in `Node.js` environment, whose version is `12.18.3` now.**

### My VSCode Environment

```
Version: 1.55.1 (user setup)
Commit: 08a217c4d27a02a5bcde898fd7981bda5b49391b
Date: 2021-04-07T15:06:02.360Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19041
```

Fortunately, there is an option in the ESLint extension of VSCode to specify the runtime library that VSCode called (i.e. the built-in Node.js or the external ones that user installed), but to enable this option, user still have to manually select the current runtime in the GUI.

Here is the description of this option (`eslint.runtime`):
> The location of the node binary to run ESLint under.
>
> - When specified as a user/machine setting, the Node version from `eslint.runtime` automatically replaces the built-in version.
> - When specified as a workspace setting, `eslint.runtime` allows you to switch to use that version with the `ESLint: Select Node version command`.

### Solution 1

To change the syntax of the `cactbot-output-strings.js`, not to use the brand new syntax, so that VSCode would be happy with the elder syntax.
(There are only 2 place that use the new syntax, so I think it is not difficult to make the change)

### Solution 2

Let user change the `eslint.runtime` option in their own machine, this bug would also be solved. So that we don't need to change any code of cactbot.
(But personally, I don't like this solution, for example, I have both Linux and Windows to develop cactbot, I would be tired to switch between different runtime paths if goes this way.)

------

FYI, cc @Trim21 @panicstevenson

**Comment by quisquous** [comment] 2021-04-13 15:46
I think "Solution 1" sounds good to me.  I think it's a small restriction for a very small number of people looking at eslint code but helps out a lot of people.

Do you think there's any way we could test this automatically and warn about it? If no, that's fine, but I was just curious if there was some way to automatically catch this problem in the future.

**Comment by panicstevenson** [comment] 2021-04-13 19:31
I'm in favor of solution 1; all it does, effectively, is "hurt" readability. I don't think the ESLint rules themselves will see a lot of traffic, but if we have them and they're throwing errors for someone that is cloning the repository and looking around, that will be a negative experience for them, certainly.

Side note: It looks as though the nullish coalescing operator (??) is also not available in that version of Node.

Going forward, I think there's a couple ways to test this:

1. Catch it in review (potentially uncaught)
1. Add a GitHub Action to test it (not caught at commit time)
1. Add a ESLint rule for the ESLint rules (unsure about how this would work, potentially easy, potentially gross)

It's definitely easy to catch; you can write anything to check these files for `?.` and `??`, but it would be a question of how much effort a solution warrants for something that will probably continue to be owned by 4 people.

**Comment by quisquous** [comment] 2021-04-14 07:07
Maybe keeping it simple and doing #1 (aka not doing anything extra) is the best plan given how few people are writing code there.

**Comment by MaikoTan** [comment] 2021-04-14 14:03
IMO, I think a Github Action make sense?
we can just run all the rules in the whole repo with nodejs v12 and v14, to catch possible bugs.

**Comment by Trim21** [comment] 2021-04-26 11:41
can;t reproduce it. eslint in vscode works fine on windows

![image](https://user-images.githubusercontent.com/13553903/116076925-749bc380-a6c7-11eb-861e-10802230f6f7.png)

**Comment by MaikoTan** [comment] 2021-05-02 14:04
> I can't reproduce it. eslint in vscode works fine on windows with same node version

Well, I was using VSCode with remote feature on Linux mostly. Let me figure out soon.

**Comment by quisquous** [comment] 2021-06-05 22:19
I think this got fixed, right? Should this be closed, or is there more followup work here that somebody wants to do?

**Comment by MaikoTan** [comment] 2021-06-05 22:41
> I think this got fixed, right? Should this be closed, or is there more followup work here that somebody wants to do?

I turn to use VSCode insider version which has Node.JS v14 built-in and didn't reproduce this issue again. After testing I think it more like a bug of VSCode itself as it happened when using remote-SSH and should be fixed in the newer version.
So I think it is okay to close this issue unless someone has met again.

**Comment by MKhayle** [comment] 2021-06-14 04:19
Hello,

I just had a similar issue while trying to use Visual Studio Code to push changes on my repository. I guess the issue also is about the new syntax which was used in [a rule added one week ago](https://github.com/quisquous/cactbot/blob/main/eslint/cactbot-matches-type-references.js). Looks like the solution 1 would also work here.

```
C:\Users\Khayle\source\repos\cactbot\eslint\cactbot-matches-type-references.js:6
  return currentTrigger.properties.find((property) => property.key.name === 'id')?.value.value;
                                                                                  ^

SyntaxError: Unexpected token '.'
    at new Script (vm.js:88:7)
    at NativeCompileCache._moduleCompile (C:\Users\Khayle\source\repos\cactbot\node_modules\v8-compile-cache\v8-compile-cache.js:240:18)
    at Module._compile (C:\Users\Khayle\source\repos\cactbot\node_modules\v8-compile-cache\v8-compile-cache.js:184:36)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (C:\Users\Khayle\source\repos\cactbot\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at C:\Users\Khayle\source\repos\cactbot\node_modules\eslint-plugin-rulesdir\index.js:30:103
    at Array.reduce (<anonymous>)```

Thanks for your work.

**Comment by Trim21** [comment] 2021-06-14 04:57
@MKhayle what's your vscode and node version？

**Comment by MKhayle** [comment] 2021-06-14 05:13
This is logged by a git pre-commit hook : 
![image](https://user-images.githubusercontent.com/4359469/121842050-ebc10180-ccdf-11eb-8849-38874b268ce7.png)


Node in terminal : v12.18.2
VS Code : 
```Version: 1.57.0 (user setup)
Commit: b4c1bd0a9b03c749ea011b06c6d2676c8091a70c
Date: 2021-06-09T17:18:42.354Z
Electron: 12.0.9
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19041```

**Comment by Trim21** [comment] 2021-06-14 05:19
this has nothing to do with vscode

better upgrade nodejs to v14

**Comment by MaikoTan** [comment] 2021-06-14 05:30
@MKhayle What is your workspace by the way?
I found I have only met this problem when I am using `remote-SSH` feature of VSCode and connecting to a Linux machine (or Debian 9, precisely).

**Comment by panicstevenson** [comment] 2021-06-14 05:37
Should we set the node version in package.json to be >=14? Otherwise I think we should downgrade these to work with node 12

**Comment by Trim21** [comment] 2021-06-14 05:42
> Should we set the node version in package.json to be >=14? Otherwise I think we should downgrade these to work with node 12

Set node to >=14 I think

**Comment by MaikoTan** [comment] 2021-06-14 05:42
> Should we set the node version in package.json to be >=14? Otherwise I think we should downgrade these to work with node 12

Since v14 is already the LTS, I think it is worth to set as mentioned.

**Comment by MKhayle** [comment] 2021-06-14 14:04
I updated my local Node version as required and it works 100% fine, thanks ! My bad for not checking that first. 

@MaikoTan I'm using VSCode on Windows 10 and was trying to commit onto GitHub, so no Linux involved at all there.

**Comment by panicstevenson** [comment] 2021-06-16 05:45
For what it's worth, Node >= 14 is actually [already defined](https://github.com/quisquous/cactbot/blob/main/package.json#L83). I wonder if there's a good way to prevent this being an issue going forward. (For instance, if we were to close this issue and someone else runs into it).

**Closed** 2022-04-10 07:20 UTC
Labels: bug
