### ISSUE TITLE
Raidboss: TEA Alpha & Beta Instructions Not Working

### ISSUE THREAD

**Issue by SJoshua** [quisquous/cactbot#1653] opened 2020-08-08 04:16 UTC
## Description

TEA Alpha & Beta Instructions aren't working. 
* No text displayed during `TEA Alpha Instructions`, `TEA Alpha Instructions Callout`, `TEA Alpha Ordained Motion 1`, `TEA Alpha Ordained Stillness 1`, `TEA Alpha Ordained Motion 2`, `TEA Alpha Ordained Stillness 2`, `TEA Alpha Safe Spot`, `TEA Alpha Resolve First Motion`, `TEA Beta Instructions`, `TEA Beta Instructions Callout`, `TEA Beta Radiant` ... (not sure about `TEA Beta Optical Stack` ~ `TEA Irresistible Grace`.)

The timeline of Perfect Alexander Phase seems to be broken too. 

Version: 0.18.4 - 0.18.6 ( I am not sure if previous versions are working. )

## Additional information

* Game Language: Japanese
* FFXIV ACT Plugin Language: Japanese
* Log: https://server.sforest.in/ffxiv/Network_20510_20200807.2020.08.08.log

( Sorry, I forgot to take screenshots. )

**Comment by quisquous** [comment] 2020-08-08 04:30
What do you mean by the timeline not working?

**Comment by SJoshua** [comment] 2020-08-08 04:38
> What do you mean by the timeline not working?

After Phase 4 Part 2 - Fate Projection β, there was still something about Fate Projection β displayed in the timeline. ( My memory might not be accurate since I was focusing on the mechanisms. )

**Comment by quisquous** [comment] 2020-08-08 04:45
Thanks for the log, that's perfect.  Looking at it, it looks like for whatever reason, Perfect Alexander doesn't have a name in the log itself.

```
03|2020-08-07T21:04:07.3810000+08:00|40005908||0|50|0|0||9042|11349|28938440|28938440|10000|10000|0|0|99.98219|96.24606|0|-4.792213E-05||3919681e26a3a66cf1b6e96420df2cfc
21|2020-08-07T21:22:04.7540000+08:00|40005908||487B|未来観測α|40005908||3C|0|49|48000|1B|487B8000|0|0|0|0|0|0|0|0|0|0|24686990|28938440|10000|10000|0|1000|99.99231|99.99231|1.192093E-07|-4.792213E-05|24686990|28938440|10000|10000|0|1000|99.99231|99.99231|1.192093E-07|-4.792213E-05|00005692|0ec3deb307f322d1ae22607b45cf1891
```

That would explain why the timeline would be off and most of the triggers involving Perfect Alexander wouldn't work.  Let me ask Ravahn and see if there's any thoughts.

Has this worked in the past? Is this repeatedly happening, or was this a one-time problem?

**Comment by SJoshua** [comment] 2020-08-08 04:50
Since my party just reached phase 4 in these days, I don't know if it worked in the past. It's repeatedly happening (as far as I see).

Btw, I recalled that there was a notification of `TEA Ordained Capital Punishment` (ja: 'タンクシェア', en: 'Shared Tankbuster') during `Fate Projection β` just before the boss became untargetable.

**Comment by quisquous** [comment] 2020-08-08 04:55
@MaikoTan Do you happen to have done TEA in Japanese? I don't really know who else to ask about cactbot in Japanese.

@KattTails Are you still doing TEA? If so, have you seen this ever? Just curious if this could be a general issue too.

**Comment by quisquous** [comment] 2020-08-08 05:07
> Btw, I recalled that there was a notification of `TEA Ordained Capital Punishment` (ja: 'タンクシェア', en: 'Shared Tankbuster') during `Fate Projection β` just before the boss became untargetable.

This is a timeline trigger, and so if your timeline is not synced, then this trigger will happen at the wrong time.  So, I think the heart of the problem is still the missing combatant name in the logs.

**Comment by KattTails** [comment] 2020-08-08 09:07
I've never experienced this as far as I can recall. Game set to English though.

**Comment by quisquous** [comment] 2020-08-08 15:59
@SJoshua Are you able to search through your logs and find examples of lines containing `|9042|` (ideally on lines that start with `03` or `04`)?  Perfect Alexander gets added at the start of the zone, so you don't need to be at phase 4 to see it.  I just want some more evidence that this is a consistent issue.

I brought this up in discord here: https://discordapp.com/channels/551474815727304704/551474815727304706/741520065190690837

**Comment by quisquous** [comment] 2020-08-08 18:17
@SJoshua If you don't mind more testing, could you add the cactbot test overlay https://quisquous.github.io/cactbot/ui/test/test.html as an overlay, and let me know if the name shows up on the `target` line when you're targeting Perfect Alexander?  (It's kind of a noisy overlay, so hopefully you could enable it during the long cutscene for one Perfect Alexander pull to verify.)

**Comment by SJoshua** [comment] 2020-08-08 19:21
> @SJoshua If you don't mind more testing, could you add the cactbot test overlay https://quisquous.github.io/cactbot/ui/test/test.html as an overlay, and let me know if the name shows up on the `target` line when you're targeting Perfect Alexander? (It's kind of a noisy overlay, so hopefully you could enable it during the long cutscene for one Perfect Alexander pull to verify.)

I am glad to test it. However, since my party completed TEA tonight, we will take a rest until 8/14. 

(As a temporary fix, I replaced the sources with empty strings and it worked. Timeline was broken tho. )

**Comment by quisquous** [comment] 2020-08-08 19:25
> I am glad to test it. However, since my party completed TEA tonight, we will take a rest until 8/14.

Congrats! :tada: 

It sounds like Ravahn has an idea what the issue is in the ffxiv plugin, so hopefully this can get fixed in the future.

**Comment by quisquous** [comment] 2020-08-08 22:03
There's a 2.0.5.14 beta plugin up at https://discordapp.com/channels/551474815727304704/551476805148737546/741756457296461895 that should fix this.

**Comment by MaikoTan** [comment] 2020-08-10 06:33
Sorry for late reaction, and I cannot offer help here.
Because business cause me did not enter TEA or even Savage in Shadowbringers.

**Comment by quisquous** [comment] 2020-08-14 16:38
SJoshua confirmed this was fixed.

**Closed by quisquous** 2020-08-14 16:38 UTC
Labels: bug
