### ISSUE TITLE
Fishing overlay freezing/crashing often

### ISSUE THREAD

**Issue by soveriegn3** [quisquous/cactbot#3904] opened 2021-12-22 15:35 UTC
## Description

Fishing overlay does not work on some fishing holes, it simply sits frozen forever. It works for one cast on said holes, then never again on those holes. On a brand new hole I tested this morning, it does work correctly (the first one in EW so far).

## Additional information

Overlayplugin log

[12/22/2021 8:55:32 AM] Info: AssemblyResolver: Loaded: HtmlRenderer, Version=0.18.0.0, Culture=neutral, PublicKeyToken=null
[12/22/2021 8:55:32 AM] Info: AssemblyResolver: Loaded: CefSharp, Version=95.7.141.0, Culture=neutral, PublicKeyToken=40c4b6fc221f4138
[12/22/2021 8:55:32 AM] Info: InitPlugin: PluginDirectory = C:\Program Files (x86)\Advanced Combat Tracker\Plugins
[12/22/2021 8:55:32 AM] Info: AssemblyResolver: Loaded: CefSharp.OffScreen, Version=95.7.141.0, Culture=neutral, PublicKeyToken=40c4b6fc221f4138
[12/22/2021 8:55:32 AM] Info: AssemblyResolver: Loaded: CefSharp.Core, Version=95.7.141.0, Culture=neutral, PublicKeyToken=40c4b6fc221f4138
[12/22/2021 8:55:32 AM] Info: AssemblyResolver: Loaded: CefSharp.Core.Runtime, Version=95.7.141.0, Culture=neutral, PublicKeyToken=40c4b6fc221f4138
[12/22/2021 8:55:32 AM] Info: AssemblyResolver: Loaded: Fleck, Version=1.2.0.0, Culture=neutral, PublicKeyToken=null
[12/22/2021 8:55:32 AM] Info: InitPlugin: Initialised.
[12/22/2021 8:55:33 AM] Info: cactbot: 0.24.7.0 C:\Program Files (x86)\Advanced Combat Tracker\Plugins\cactbot\CactbotOverlay.dll (dir: C:\Program Files (x86)\Advanced Combat Tracker\Plugins\cactbot)
[12/22/2021 8:55:33 AM] Info: OverlayPlugin: 0.18.0.0 C:\Program Files (x86)\Advanced Combat Tracker\Plugins\OverlayPlugin.dll
[12/22/2021 8:55:33 AM] Info: FFXIV Plugin: 2.6.3.3 C:\Program Files (x86)\Advanced Combat Tracker\Plugins\FFXIV_ACT_Plugin.dll
[12/22/2021 8:55:33 AM] Info: ACT: 3.5.0.273 C:\Program Files (x86)\Advanced Combat Tracker\Advanced Combat Tracker.exe
[12/22/2021 8:55:33 AM] Info: Parsing Plugin Language: en
[12/22/2021 8:55:33 AM] Info: System Locale: en-US
[12/22/2021 8:55:33 AM] Info: cactbot user directory: C:\Program Files (x86)\Advanced Combat Tracker\Plugins\cactbot\user\
[12/22/2021 8:55:33 AM] Info: Version: intl
[12/22/2021 8:55:33 AM] Info: LoadAddons: CactbotOverlay.dll: Initialized Cactbot.PluginLoader
[12/22/2021 8:55:34 AM] Info: Oopsy Overlay: BrowserConsole: RequestSync: 1640184934731 (Source: file:///C:/Program%20Files%20(x86)/Advanced%20Combat%20Tracker/Plugins/cactbot/ui/oopsyraidsy/oopsy_live.bundle.js, Line: 14742)
[12/22/2021 8:55:34 AM] Info: Mopi: BrowserConsole: ACTWS compatibility shim enabled. (Source: , Line: 28)
[12/22/2021 8:55:34 AM] Info: Mopi: BrowserConsole: Connecting... (Source: https://haeruhaeru.github.io/mopimopi/js/core.js, Line: 280)
[12/22/2021 8:55:35 AM] Info: Mopi: BrowserConsole: ChangeZone:[object Object] (Source: https://haeruhaeru.github.io/mopimopi/js/core.js, Line: 343)
[12/22/2021 8:55:38 AM] Info: Found enmity memory for 6.0.
[12/22/2021 8:55:48 AM] Info: Mopi: BrowserConsole: ChangeZone:[object Object] (Source: https://haeruhaeru.github.io/mopimopi/js/core.js, Line: 343)
[12/22/2021 9:00:33 AM] Info: fisher: BrowserConsole: failed to look up place: the Wellspring of Regret (Source: file:///C:/Program%20Files%20(x86)/Advanced%20Combat%20Tracker/Plugins/cactbot/ui/fisher/fisher.bundle.js, Line: 13301)
[12/22/2021 9:00:33 AM] Info: fisher: BrowserConsole: failed to look up place: [object Object] (Source: file:///C:/Program%20Files%20(x86)/Advanced%20Combat%20Tracker/Plugins/cactbot/ui/fisher/fisher.bundle.js, Line: 13301)

Video example (starting at a brand new hole which worked and surprised me, second hole is a "broken" one and some nice overlay crashes as well).
https://drive.google.com/file/d/13lQFBJbm07jMtpP0oZ-ejegANtsfoOpJ/view?usp=sharing

**Comment by quisquous** [comment] 2021-12-23 07:58
Hmm.  I have done some fishing and I haven't seen this happen at all.  Sorry for the bug, but it might take me a bit to get around to looking at this.

**Comment by soveriegn3** [comment] 2021-12-23 20:20
I figured it was low priority, NBD.
One thing I was trying to accomplish in order to troubleshoot was clean installing the fisher overlay. What I was struggling with is that I couldn't really locate all the folders that the fisher plugin in particular was using/writing to and I don't really care to completely nuke cactbot and have to reconfigure everything just for a small QoL overlay.
Are all of the files used by the fisher overlay just located in cactbot\ui\fisher, or is there somewhere else you need to clean out in order to "cleanly" replace the fisher overlay with the stock files from cactbot?

**Comment by quisquous** [comment] 2021-12-23 20:23
There's also the indexeddb database.  See #3894 for details.

**Comment by soveriegn3** [comment] 2021-12-25 01:20
Some further documentation. I removed the subfolder inside of IndexedDB "file__0.indexeddb.leveldb". After doing that I fired ACT back up, and loaded the fisher overlay (which made a new file__0.indexeddb.leveldb folder). That however did not fix the problem. The broken fishing holes still don't work at all on the fishing overlay.

**Comment by quisquous** [comment] 2022-04-09 19:38
I think the broken holes are a duplicate of #3998 as well (which was filed later, but I think describes the issue better).  I'm going to close this issue in favor of that one.  Sorry for not having any time for the fisher overlay, but I'd be happy to take fixes if anybody else has them.

**Closed by quisquous** 2022-04-09 19:38 UTC
Labels: bug, help wanted, fishing🎣
