### ISSUE TITLE
Jobs buff icons are showing even when disabled

### ISSUE THREAD

**Issue by Araiia** [quisquous/cactbot#3851] opened 2021-12-15 06:31 UTC
## Description

As of the 12/14 update, I'm seeing the buff icons at default size and unable to resize or hide them with the 'only show the party buff tracker' option. When a tracked buff is active in combat, it is resized, but I'm still unable to hide them. 

## Additional information

If available, please include any logs or screenshots depicting the issue you're experiencing.
Out of combat (I have the opacity set to 0.5): 
![image](https://user-images.githubusercontent.com/41348845/146134731-fc2d6d1e-8fc8-47f0-95b4-81d9707d7272.png)
In combat: 
![image](https://user-images.githubusercontent.com/41348845/146134771-fe13cf79-8c5d-4421-9789-86d6231550f8.png)
In combat with dot active:
![image](https://user-images.githubusercontent.com/41348845/146134858-3014189a-75d4-464a-a9e1-e82bbcc634db.png)
Plugin options: 
![image](https://user-images.githubusercontent.com/41348845/146134912-1b6b1cda-d96f-46ca-9de8-6952d93b1ff2.png)

**Comment by MaikoTan** [comment] 2021-12-15 06:54
This is already fixed in #3849 , sorry for that.
Although the changes have not released yet.

**Comment by quisquous** [comment] 2021-12-15 06:56
This is a duplicate of #3848.  I'll push a release.

**Closed by quisquous** 2021-12-15 06:56 UTC
Labels: bug
