### ISSUE TITLE
Feature Request: Job details return proper data?

### ISSUE THREAD

**Issue by MaikoTan** [quisquous/cactbot#2549] opened 2021-03-07 07:41 UTC
Most of the properties in the `JobDetail` data currently accepted by the JS front-end are simple and easy to understand, such as PLD's `oath` which is a number, and MCH's `overheatActive` which is obviously a boolean value.
But there are also some less clear properties, such as `arcanums` for AST and `steps` for DNC, which in theory should be arrays of strings, but currently, the C# backend returns data as strings split by ", ", which makes it difficult for the JS frontend to traverse and calculate the data.
Therefore, could this data be output to the front end in the correct way (i.e. as an array of strings)?

Translated with www.DeepL.com/Translator (free version)

**Comment by quisquous** [comment] 2021-03-07 18:25
Yeah, I agree that it would probably be better to send an array of strings than a string you have to split.  The tricky part here is that changing what the plugin returns is tricky.

One option is to change the plugin code to send arrays of strings and the jobs code to handle either arrays of strings or a string you need to split (for backwards compatibility with people who don't have the new plugin).  But then the jobs code still has to handle the string you have to split, so I'm not sure this is a good approach.

Another option is something like:
1) change the plugin code to return a duplicate old path called something like `arcanumsOld` which sends what is in `arcanums` now, and is a duplicate of `arcanums`
2) change the jobs code to look for both of these paths
3) release the plugin
4) change the plugin code to return an array of strings for `arcanums`, change the jobs code to use `arcanums` as an array of strings
5) remove the plugin code for `arcanumsOld`, `, remove the jobs code for `arcanumsOld`
6) release the plugin again

During step #5 the github.io version would not work, so probably 5+6 need to be done very close together in time.

**Comment by MaikoTan** [comment] 2021-03-08 00:54
So it's easy to change the structure of the returned data, right? (I'm not really familiar with C#)
It's just that backwards compatibility isn't easy to deal with?
I was thinking that instead of renaming an existing property to `arcanumsOld`, leave it as is and name the new one something else, like `arcanumsList`?

Then on the JS side we can detect if the new property exists or not and use the new one if possible. When the time is right, we just remove the compatibility code.

**Comment by quisquous** [comment] 2021-03-08 22:50
Yes, that's possible to do.  The only argument against it is that you'd need to support both on both sides, and so it doesn't necessarily make the code any simpler in the short term.  The question is really "is this enough of a pain to do right now, or maybe worth waiting for the expansion when everything is broken anyway".

**Comment by MaikoTan** [comment] 2021-03-09 09:16
Sure.
I can open up such a pull request first, and then you merge it when patch 5.5 update.

**Closed** 2021-04-15 06:40 UTC
Labels: enhancement
