### ISSUE TITLE
TypeError: Cannot read property 'groups' of undefined

### ISSUE THREAD

**Issue by jchrisrogers** [quisquous/cactbot#756] opened 2019-11-14 16:28 UTC
## Description

The following error shows when running the raidboss module's test at Summerford Farms

`[11/14/2019 10:00:04 AM] Info: DBM: BrowserConsole: Uncaught TypeError: Cannot read property 'groups' of undefined (Source: file:///D:/Advanced%20Combat%20Tracker/cactbot/ui/raidboss/popup-text.js, Line: 281)`

## Additional information

I have the following ACT plugins (in order shown under Plugin Listing)

FFXIV_ACT_Plugin
OverlayPlugin (ngld)
CactbotOverlay
UniversalisPlugin
ACT_DiscordTriggers
ACTWebSocket

**Comment by quisquous** [comment] 2019-11-18 01:33
This is a duplicate of #758

**Closed by quisquous** 2019-11-18 01:33 UTC
Labels: bug
