### ISSUE TITLE
Latest fisher module not working

### ISSUE THREAD

**Issue by Akurosia** [quisquous/cactbot#1880] opened 2020-10-15 16:32 UTC
After the commit https://github.com/quisquous/cactbot/commit/8432fbcb7bb03604652fd6b6861ba6a5af0ae531, the fisher overlay is no longer working for me.
The errors i got are: 
```
[15.10.2020 18:29:06] Info: fischer: BrowserConsole: Uncaught TypeError: Cannot read property 'IQRHookQuantity' of undefined (Source: file:///E:/FINAL%20FANTASY%20XIV%20-%20A%20Realm%20Reborn/AdditionalExtern/ACT/Plugins/OverlayPlugin_ngld/cactbot/ui/fisher/seabase.js, Line: 274)
[15.10.2020 18:29:06] Info: fischer: BrowserConsole: Uncaught TypeError: Cannot read property 'IQRTugQuantity' of undefined (Source: file:///E:/FINAL%20FANTASY%20XIV%20-%20A%20Realm%20Reborn/AdditionalExtern/ACT/Plugins/OverlayPlugin_ngld/cactbot/ui/fisher/seabase.js, Line: 318)
```
It worked with an older version but not with the latest one (even made sure to update fisher data by using the gen_fisher data script)
@panicstevenson could you have a look at this?

**Comment by Akurosia** [comment] 2020-10-15 16:51
ok i found a workaround but pls double check this:

my workaround is to specify following in the `queryTug` and `queryHookTimes` method `let _this = this` and than change the `this.options.IQRHookQuantity` to `_this.options.IQRHookQuantity`

**Comment by panicstevenson** [comment] 2020-10-15 17:04
Apologies; I've never used the Fisher module before, so I thought loading it up was enough of a test to make sure that change didn't have any issues. The code seemed straightforward enough so I didn't give it another thought.

The issue is because of the `this` binding within the Promise. I think your workaround would be the common fix for this, short of switching to something that maintains `this`. I have the same fix ready to land that I'm willing to push up, but I wanted to give you a chance to push it up first, since you fixed it yourself

**Comment by Akurosia** [comment] 2020-10-15 17:08
i wrote with @quisquous and the answer was 
```
There's probably a better fix here, tbh
using bind or arrow functions or something
```
If you can workout a solution that way, i think all of us were happy, if not i would wait for @quisquous to give this solution a go.

**Comment by panicstevenson** [comment] 2020-10-15 17:27
That's fair, and I'm inclined to agree since this issue somewhat stemmed from the quirks of not using those to preserve `this`. I have a PR ready, if you'd be able to test it that'd be great. I used it, but I'm not familiar with the Fisher module enough to know what it should look like.

**Closed** 2020-10-16 16:02 UTC
Labels: bug
