### ISSUE TITLE
old content wont work for some reason even tho they are all enabled 

### ISSUE THREAD

**Issue by kaidachan** [quisquous/cactbot#5763] opened 2023-08-11 07:27 UTC
## Description
i have all the expansions enabled on my catcbot yet no expansion works other than end walker can someone help please ?
Description of the issue you're seeing.

## Additional information

If available, please include any logs or screenshots depicting the issue you're experiencing.

**Comment by xiashtra** [comment] 2023-08-12 08:21
duplicate of #5762

**Closed** 2023-08-15 00:02 UTC
Labels: bug
