### ISSUE TITLE
CI: Husky pre-commit hook fails when running in Github for Windows

### ISSUE THREAD

**Issue by JLGarber** [quisquous/cactbot#1568] opened 2020-07-15 05:06 UTC
When attempting to commit to cactbot while using Github for Windows, it fails with:
```
Commit failed - exit code 1 received, with output: 'husky > pre-commit (node v13.9.0)
Path/To/GitHub/cactbot/node_modules/.bin/lint-staged: line 5: cygpath: command not found
internal/modules/cjs/loader.js:983
  throw err;
  ^

Error: Cannot find module 'D:\lint-staged\bin\lint-staged.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:980:15)
    at Function.Module._load (internal/modules/cjs/loader.js:862:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
husky > pre-commit hook failed (add --no-verify to bypass)'
```

However, committing from the command line correctly invokes the hook and successfully commits.

From a little searching around, it looks like this is [due to restrictions on PATH when invoked by the Github for Windows GUI.](https://stackoverflow.com/a/43371374). It's entirely possible that my Node installation is incorrect, but I'm not knowledgeable enough to troubleshoot that.

This doesn't directly block me, since the command line *is* available, but I do like the Github for Windows client, and if it's possible I would like to continue using it.

**Comment by quisquous** [comment] 2020-07-15 06:23
This sounds like the same thing @VanSlanzar was running into, except in `C:\lint-staged\` .

Ping @panicstevenson for thoughts?

**Comment by VanSlanzar** [comment] 2020-07-15 07:00
Yes, same error With client Windows, `C:\lint-staged\`.
I like use it, i hope il Will be fixed.

**Comment by panicstevenson** [comment] 2020-07-15 23:43
I just downloaded GitHub for Windows and I can't reproduce this.

How was node originally installed? I'd try to do `which node` and `which node.exe` to ensure both exist and are in reasonable places.

**Comment by panicstevenson** [comment] 2020-07-15 23:45
Also, potentially:

https://git-scm.com/download/win if it can't find cygpath ?

**Comment by JLGarber** [comment] 2020-07-16 05:29
I installed node using the x64 msi installer. I have the windows install for Git already, unfortunately, so it's likely that isn't the issue.

`npm-which node/npm-which node.exe` both return `C:\Program Files\nodejs\node.EXE`, which is presumably correct? That location is (I assume correctly?) in PATH.

I suppose I can try a complete Node re-install and see whether anything changes.

**Comment by panicstevenson** [comment] 2020-07-16 05:38
> both return C:\Program Files\nodejs\node.EXE

Both have .exe? I couldn't say if that's _correct_ or not, but it definitely differs from what both I and @quisquous have.

```
which node
/c/Program Files/nodejs/node
```

```
which node.exe
/c/Program Files/nodejs/node.exe
```

**Comment by JLGarber** [comment] 2020-07-16 06:06
Whrrgh. So it looks like the output from `cmd` is different from `Git Bash`. `cmd` returns what I noted, `Bash` returns your output. I'm guessing that's likely a dead end.

Reinstalling Node didn't seem to cause any changes, so I'll probably have to try reinstalling Github for Windows next to see whether that makes a difference. If it continues to be broken, I guess I can move to a different client. Frustrating but doable.

**Comment by panicstevenson** [comment] 2020-07-16 06:25
Hmmm; well, it definitely works for me as I think we'd expect the path to go down. I'm assuming Windows 10? I only ask because some people actively refuse to ever upgrade, even the game that they authored a plugin for no longer officially supports it 👀

**Comment by panicstevenson** [comment] 2020-07-16 06:28
Oh! Does that mean you did `npm install` from cmd?

**Comment by JLGarber** [comment] 2020-07-16 06:37
Fair point, but no, I'm on Windows 10. 

No, I did run `install` from Bash. (I typically run other commands in `cmd` because I'm lazy and always invoked Bash from the right-click context menu, while cmd is simply Win-R and then Enter. I suppose it would be best to simply switch over to using Bash generally...)

**Comment by panicstevenson** [comment] 2020-07-16 06:47
I'll spin up a virtual machine tomorrow and see where I get and document my steps; I'd like to rule out anything I've done that I don't remember as intermediate steps. Overall, if this is causing a good amount of pain for people then we should probably consider reverting it and moving more validation server-side. I understand this isn't the highest traffic repository on GitHub, but if someone was making their first contribution and couldn't and silently gave up over this I'd feel pretty terrible.

**Comment by JLGarber** [comment] 2020-07-16 06:58
I appreciate it. I'll change over my workflow if I have to, but if it's something obvious that I'm missing I'd prefer to fix it before getting used to a new workflow. Thanks for taking the time to look into this!

**Comment by VanSlanzar** [comment] 2020-07-16 16:48
Good evening, as far as I'm concerned, everything is installed on the `C: \` system hard drive. I installed npm with Gitbash `npm install`. In addition, the latest versions of node and python are installed. If you need more information, I will try to answer you as best I can.

**Comment by panicstevenson** [comment] 2020-07-16 20:28
I was able to replicate this within a virtual machine of a fresh Windows 10 install:
```
Windows 10 Enterprise 64-bit Version 1903
Git for Windows v2.27.0
GitHub Desktop for Windows 10 v2.5.3
Node LTS Windows MSI v12.18.2
```
I used 100% default installations, cloned my repository via GitHub Desktop, and ran `npm install` via Git Bash.
I assume this is a close enough mirror to the conditions both of you are in.
```
Commit failed - exit code 1 received, with output: 'husky > pre-commit (node v12.18.2)
/c/.../GitHub/cactbot/node_modules/.bin/lint-staged: line 5: cygpath: command not found
internal/modules/cjs/loader.js:969
  throw err;
  ^

Error: Cannot find module 'C:\lint-staged\bin\lint-staged.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
    at Function.Module._load (internal/modules/cjs/loader.js:842:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
husky > pre-commit hook failed (add --no-verify to bypass)'
```
Playing around with things in this state, running `npm install` vs `npm.cmd install` I couldn't get things exactly to a state where things were fixed; additionally, I didn't want to edit PATH variables. I changed a few settings within GitHub Desktop, but those didn't affect anything either. Essentially, I didn't want any fix that was still going to impact the next user and they would have to figure it out or find this issue or give up. Ultimately the change would have to be that `husky` invoking `lint-staged` directly wouldn't work and that it had to be hoisted up to `npm` where _something_ would know about the environment necessary. `npm run lint-staged` doesn't work, since that would be a user-defined script that we don't have. However, `npx lint-staged` _does_ work. At least, it does for me, on all of my (now three) setups.

Before opening a PR and calling this fixed for a workflow that I don't use, I'd like to invite you both to changing the following code snippet within [package.json](https://github.com/quisquous/cactbot/blob/master/package.json#L159):
```
"husky": {
  "hooks": {
    "pre-commit": "lint-staged"
  }
},
```
to:
```
"husky": {
  "hooks": {
    "pre-commit": "npx lint-staged"
  }
},
```
And see if that fixes your issues. The biggest issue I have seen with this is that it increases the time and cpu utilized of running pre-commit executions:
```sh
$ time lint-staged
ℹ No staged files found.
lint-staged  0.19s user 0.08s system 34% cpu 0.771 total
```
vs
```sh
time npx lint-staged
npx: installed 97 in 3.824s
ℹ No staged files found.
npx lint-staged  3.73s user 2.18s system 109% cpu 5.409 total
```
There's a relatively simple fix, which requires the developer to run:
```
npm install -g lint-staged
```
```
time npx lint-staged
ℹ No staged files found.
npx lint-staged  0.20s user 0.08s system 89% cpu 0.311 total
```
But unfortunately I don't know of a way to disseminate that information in such a way that all users would know to install `lint-staged` globally.

Let me know how that fix works for you @JLGarber @VanSlanzar, and let me know if you find the trade-offs acceptable @quisquous. If not, we might be able to find another path forward.

**Comment by JLGarber** [comment] 2020-07-17 01:22
Changing the command in `package.json` resolves the issue, while unfortunately a global install of `lint-staged` does not. (I specifically tested both with and without files containing lint issues, and invoking with `npx` correctly failed or committed in each case.)

**Comment by panicstevenson** [comment] 2020-07-17 01:40
There was only one solution for the time being, the `npx lint-staged`; the `npm install -g lint-staged` simply makes `npx lint-staged` faster, which kind of sucks since it'll be non-obvious for anyone committing that their commits can be <1 second instead of ~5 seconds.

**Comment by JLGarber** [comment] 2020-07-17 01:43
Ah, I misunderstood what problem the simple fix from a global installation was fixing! If nothing else, if quisquous approves this change, we can at least recommend a global install in the contribution guide.

**Comment by quisquous** [comment] 2020-07-17 03:08
I feel similar to panic's thoughts above about "if someone was making their first contribution and couldn't and silently gave up over this I'd feel pretty terrible".  I think "working by default but slow" is an infinitely better option than "fast for some but broken for others", especially when there's a workaround we can document.

**Comment by quisquous** [comment] 2020-07-17 03:10
I mean, the other option also is that the husky option is not useful for other people.  I think I would want to give it a few months, and then if folks felt like it was more of a pain than a help, I'd be open to turning it off.  It's really there to just give early warning about what the github actions will tell you later.

**Comment by panicstevenson** [comment] 2020-07-17 03:13
> It's really there to just give early warning about what the github actions will tell you later.

In this same vein, you could always turn it off or bypass it; I also realized when I was troubleshooting that you could just _not_ `npm install` and you'd never have to worry about husky again. 😇

I think maybe there could be some documentation in the contributions guide that if you're absolutely stuck on a problem you could open a PR bypassing the client-side validation and have the server-side validation break and we could discuss it further? That feels kind of bad, but if you're stuck and don't have the means to contact anyone directly, I think you're kind of left to fend for yourself, which also feels bad.

**Comment by quisquous** [comment] 2020-07-17 03:25
Yes, definitely.  I think that would be good to spell out that using `--no-verify` if you're stuck is an option.

**Comment by JLGarber** [comment] 2020-07-17 03:40
From a contributor perspective, it's nice to be *able* to run `npm install` if only to allow for live linting within the editor. Not that this has completely avoided build failures for me, but it's definitely reduced them. (I can't say I've been as consistent about use of `npm run test` as I should be, but it has saved a few commits.)

 Personally, I (theoretically) like the idea of continuing to use Husky, both because it's faster to fail for the user than the repository CI, and because it (maybe?) ultimately could mean fewer superfluous notifications for quisquous. (Potentially a lot of them, given that people most likely to commit unlinted content are also those most likely to be using GUI tools rather than the command line. Or at least it seems more likely. Not that I have personal experience there or anything.)

**Closed** 2020-07-17 03:49 UTC
Labels: bug
