### ISSUE TITLE
Tripped this Error Today

### ISSUE THREAD

**Issue by Zeyyagga** [quisquous/cactbot#415] opened 2019-05-29 03:31 UTC
https://i.gyazo.com/cb87dd567ef27e7db19bfdc8d2266ea5.png

This popped up in the middle of raid tonight, any ideas what it is / means?

**Comment by Zeyyagga** [comment] 2019-05-29 03:35
went and looked at the file and this is whats there:

https://i.gyazo.com/243a0e72d9f80aea04477455caedba3b.png

Not sure what happened everything has been fine and working usually... 🤔

**Comment by Zeyyagga** [comment] 2019-05-29 22:01
Just realized that was the wrong line... this is the correct one:

https://i.gyazo.com/3844ee88d236c3f9d9026676489af60e.png

**Comment by Zeyyagga** [comment] 2019-05-29 22:05
Re-downloaded the yojimbo release and checked if this line was still present, and it was, starting up act the error doesnt show....

but last night raidboss stopped workin while it was showing that.

**Comment by DrLippe** [comment] 2019-05-30 20:41
This bug does occur if ttsText is not `null` and not a string.
Checking whether the type of ttsText is a string or not will solve this Error.

```
if (typeof ttsText === 'string' && playSpeech) {
  ttsText = ttsText.replace(/[#!]/, '');
  let cmd = { 'say': ttsText };
  OverlayPluginApi.overlayMessage(OverlayPluginApi.overlayName, JSON.stringify(cmd));
}
```

**Comment by Zeyyagga** [comment] 2019-05-30 20:55
You lost me friend... what should I do? :think

**Comment by Zeyyagga** [comment] 2019-05-30 21:00
Gonna assume I should change mines to read "typeof ttsText === 'string' && playSpeech"

**Comment by quisquous** [comment] 2019-06-01 02:05
I think my confusion here is why is this happening? Do you have custom triggers in your **cactbot/user/** folder? When was this popping up?

**Comment by DrLippe** [comment] 2019-06-01 12:47
Maybe a function that returns a number or something? Another solution for this problem might be
```js
if (ttsText && playSpeech) {
  ttsText = ttsText.toString().replace(/[#!]/, '');
  let cmd = { 'say': ttsText };
  OverlayPluginApi.overlayMessage(OverlayPluginApi.overlayName, JSON.stringify(cmd));
}
```

**Comment by quisquous** [comment] 2019-06-09 21:21
I mostly just want to understand what the problem is.  If there's some busted trigger that's emitting bogus tts, I'd rather go fix that instead of just adding something to silently ignoring it.

**Comment by quisquous** [comment] 2019-06-22 21:15
Just wanted to check back here and wanted to ask when this was happening, or if you have custom triggers?

**Comment by quisquous** [comment] 2019-08-08 05:01
Let me know if you have any more details about what's going on here and might be causing this.  I'm going to close this for now as there hasn't been any followups for a while.

**Closed by quisquous** 2019-08-08 05:01 UTC
