### ISSUE TITLE
Radar doesn't work without a user config in place

### ISSUE THREAD

**Issue by deice** [quisquous/cactbot#852] opened 2019-12-13 17:55 UTC
Radar module leads to errors when loading if you haven't set up a user config in cactbot/user. It  tries to check for rank keys in a non-existent config object.

Fixed my personal copy changing two lines, in AddMonster & UpdateMonsterDom functions to check for the existence of RankOptions before accessing it:

    if (options.RankOptions && monster['rank'] in options.RankOptions) // option overwrite

**Comment by Tykku** [comment] 2019-12-13 19:09
Fix tested on my end, works fine here.

**Comment by quisquous** [comment] 2019-12-13 22:02
Duplicate of #845.  Should be fixed now.

**Closed by quisquous** 2019-12-13 22:02 UTC
Labels: bug
