### ISSUE TITLE
O7s Timeline desynced after 4.3 update

### ISSUE THREAD

**Issue by Pirate144** [quisquous/cactbot#123] opened 2018-05-24 08:15 UTC
See title, happened to the other 4 people in my raid group using cactbot as well. Seems like it didn't sync up at the divergent points, and just played the default timeline with no syncs in it.

**Comment by briteside74** [comment] 2018-05-24 11:10
I just cleared O7S and experienced the same issue. Dadaluma first program but timeline continued with Biblios. When Airforce program was happening timeline was at Ultros.

**Comment by Hoshiyuu** [comment] 2018-05-24 13:58
I think specifically the Timeline couldn't complete the "guess" for the first airforce/squid and just bork completely afterwards.

**Comment by jerrybotticelli** [comment] 2018-05-24 18:58
Earlier today in the FFLogs Discord Ravahn was made aware of this. 

> Interesting.  Yes - 00:2aae is combat log text.  the lack of 1A: line for this is a problem.
The missing Actor name on 1A lines (where "from  " doesnt have the name)  is a complex issue, but is technically by design.  This will happen if the plugin cannot find the combatant name of the source of the buff/debuff.  There probably isnt anything I can do about this without introducing an additional explicit delay into the buff tracking code in the network parser, which I would prefer not to do, since it would delay triggers.(edited)
regarding the missing 1A line, the only way I'm going to be able to track this down is if someone can reproduce it with the 'dump full network data' option turned on.  I'll see if I can get someone to run O7S with it on and get me a nice big logfile out of it.

**Comment by Jolkien** [comment] 2018-05-25 02:33
Just wanted to say that I had the same issue as well. Is it something that could potentially be fixed ? Ravahn statement doesn't appear to be sure if it's fixable.

**Comment by xDemonessx** [comment] 2018-05-25 02:37
Also confirming, the timeline listed the correct order, however the call was incorrect - e.g. Airforce in timeline, but Ultros in the text popup. Very confusing.

**Comment by briteside74** [comment] 2018-05-25 03:05
08s is desynched as well

**Comment by quisquous** [comment] 2018-05-25 03:15
What do you mean by o8s being desynced? (Do you have video?) I think o7s here is weird because it's using 1A "gains the effect" lines to sync up.  o8s only uses ability usage ids, so I'm not sure I understand what's going wrong there.

**Comment by Brainlazy** [comment] 2018-05-25 03:34
Didn't see any issue in o8s tonight. Only had the o7s desync from buffs being missed due to the 00:2aae issue linked above.

**Comment by Pirate144** [comment] 2018-05-25 05:05
Had no problems with 08s either.

**Comment by ThanatosIruga** [comment] 2018-05-25 16:20
I'm experiencing the same issue in O7S, sometimes it syncs right, but the other mechs are 
inverted.

**Comment by Jolkien** [comment] 2018-05-25 22:59
I wonder if it's something that can be fixed or should we try and learn 07s by heart seeing the reason why it happens a bit higher in the thread.

**Comment by quisquous** [comment] 2018-05-25 23:05
It could be fixed by changing the triggers to match 00 lines and not the 1A lines, but in general the 1A lines show up before the 00:2aee lines and I've seen the 00 lines get dropped and not parsed.  So, I'm not keen on using them if I don't have to.

So, the answer is yes, this could be fixed, but I'm going to give ravahn a chance to fix this in the ffxiv plugin first before changing a ton of triggers.  Sorry for this being broken in the meantime.

**Comment by Jolkien** [comment] 2018-05-25 23:10
Ah nice to know it could be fixed. I REALLY appreciate the work you'Ve put in this, I know nothing of coding and this tool has me immensely useful. Hopefully I did not come as being entitled too much or anything. Thanks for the answer :)

**Comment by Brainlazy** [comment] 2018-05-26 04:32
If you want a temp fix try adding this to your user/raidboss.js
`Options.Triggers = [
{
	zoneRegex: /Sigmascape V3\.0 \(Savage\)/,
	timeline: `
		50 "--sync--" sync /00:2aae:The Guardian gains the effect of Dadaluma Simulation/ jump 1050
		510 "--sync--" sync /00:2aae:The Guardian gains the effect of Bibliotaph/ jump 2510       # Bibliotaph buff, jump to A1
		510 "--sync--" sync /00:2aae:The Guardian gains the effect of Dadaluma/ jump 3510         # Dadaluma buff, jump to A2
		1482 "--sync--" sync /00:2aae:The Guardian gains the effect of Bibliotaph/ jump 4482       # Bibliotaph buff, jump to B1
		1482 "--sync--" sync /00:2aae:The Guardian gains the effect of Dadaluma/ jump 5482         # Dadaluma buff, jump to B2
	`,

	triggers: [
	      {
      regex: / 00:2aae:The Guardian gains the effect of Dadaluma Simulation/,
      condition: function(data, matches) { return !data.first || data.seenVirus && !data.second },
      run: function(data) {
        if (data.seenVirus)
          data.second = 'dada';
        else
          data.first = 'dada';
      },
    },
    {
      regex: / 00:2aae:The Guardian gains the effect of Bibliotaph Simulation/,
      condition: function(data, matches) { return !data.first || data.seenVirus && !data.second },
      run: function(data) {
        if (data.seenVirus)
          data.second = 'biblio';
        else
          data.first = 'biblio';
      },
    },
    {
      regex: / 00:2aae:The Guardian gains the effect of Virus/,
      run: function(data) {
        data.seenVirus = true;
      },
    },
    ],
  },
]`

**Comment by IllidraEthorn** [comment] 2018-05-26 23:42
Seems like it was fixed with the ravahn's plugin's 1.7.0.10 update. I just did o7s last night and everything worked as it did before.

**Comment by Hoshiyuu** [comment] 2018-05-27 00:00
#126 Is now broken in a different way, since while the 1A: line is back, the Doom duration itself is inaccurate (9999 second)

**Comment by quisquous** [comment] 2018-05-27 13:41
This seems like it is fixed now.  I'll close this issue and leave the doom one open until that is fixed.

@Jolkien You didn't come off that way at all.  Just wanted to apologize for wanting to wait on ravahn and leaving things broken.  ravahn is awesome and came through super quickly, so I think that was the correct decision.  :)

**Closed by quisquous** 2018-05-27 13:41 UTC
