### ISSUE TITLE
Raidboss Module "struggling" to show.

### ISSUE THREAD

**Issue by FioX094** [quisquous/cactbot#799] opened 2019-11-24 22:55 UTC
## Description

Since changing to new OV for the new cactbot version, timelines / warning are not showing up most of the time.
Sometimes it does show for 2-3 second then disappears off.  Then shows up 5 seconds later but the timeline seems to be starting from the very start instead of continuing. It seems that it is not only struggling to detect when the fight starts it also seems to struggle to detect that we are still on-going.

The test file works fine, it is displaying all the details but the raidboss module just won't "start". No errors in the console from what I can see.

## Additional [information]
https://imgur.com/a/ZWW4H7j

[24/11/2019 22:40:28] Info: InitPlugin: PluginDirectory = D:\Program Files (x86)\Advanced Combat Tracker\ov
[24/11/2019 22:40:28] Info: InitPlugin: Initialized.
[24/11/2019 22:40:30] Info: cactbot: 0.13.0.0 
[24/11/2019 22:40:30] Info: OverlayPlugin: 0.10.1.0 
[24/11/2019 22:40:30] Info: FFXIV Plugin: 2.0.4.4 D:\FFXIV_ACT_Plugin.dll
[24/11/2019 22:40:30] Info: ACT: 3.4.5.265 D:\Program Files (x86)\Advanced Combat Tracker\Advanced Combat Tracker.exe
[24/11/2019 22:40:30] Info: Language: en
[24/11/2019 22:40:30] Info: LoadAddons: CactbotOverlay.dll: Initialized

**Comment by quisquous** [comment] 2019-12-12 16:54
Sorry for not following back up on this.  Is this still happening? Does it work in summerford farms if you do a /countdown?

**Comment by quisquous** [comment] 2019-12-23 05:27
I think this is a duplicate of #393 and should be fixed by 7c86b055425.

**Closed by quisquous** 2019-12-23 05:27 UTC
Labels: bug
