### ISSUE TITLE
Fisher: Overlay issue with certain Ultima Thule fishing holes

### ISSUE THREAD

**Issue by NolanSeryn** [quisquous/cactbot#3998] opened 2022-01-08 09:50 UTC
Description

I noticed that the overlay seems to 'hang' and not display the usual rolling timer on some fishing holes. In most cases, it will display normally while the spot is 'unidentified fishing hole', but once the name is revealed, the timer freezes and doesn't update for that hole again.

I've managed to isolate it to a few fishing spots in Ultima Thule, all of which are using Greek letters (α, β, γ).
For example, the timer for Limne 18 displays fine, but Limne 3-α does not - or 3-β, apohelos 18-β, etc etc. It displays normally while any of these were 'unidentified', but once the name was revealed with the Greek lettering, the overlay seemed to not know what to do with it.

At the time of this report, the last update hasn't fixed it, so I think it simply slipped through. My ACT parsing language is set to English, as well. ACT logs look normal on the "you cast your line at [fishing hole] chat messages as well, and ACT's as up to date as can be.

I unfortunately can't seem to provide any screenshots of the 'frozen' overlay either, because...the timer just doesn't show up on the affected locations. I guess the plugin doesn't even recognize that I'm at a viable fishing spot due to the potential name-reading issue.

I'd be happy to provide any other info I can, if for some reason this bug isn't able to be duplicated. Thanks!

Edit for additional info: the debug log under OverlayPlugin.dll in ACT (I was fishing at Limne 3-β) :
"[1/8/2022 5:23:24 AM] Info: Fisher: BrowserConsole: placemissing in catch (Source: file:///C:/Users/Drago/AppData/Roaming/Advanced%20Combat%20Tracker/Plugins/cactbot-0.16.5/cactbot/ui/fisher/fisher.bundle.js, Line: 13303)
[1/8/2022 5:23:29 AM] Info: Fisher: BrowserConsole: failed to look up place: [object Object] (Source: file:///C:/Users/Drago/AppData/Roaming/Advanced%20Combat%20Tracker/Plugins/cactbot-0.16.5/cactbot/ui/fisher/fisher.bundle.js, Line: 13376)
[1/8/2022 5:23:29 AM] Info: Fisher: BrowserConsole: failed to look up place: [object Object] (Source: file:///C:/Users/Drago/AppData/Roaming/Advanced%20Combat%20Tracker/Plugins/cactbot-0.16.5/cactbot/ui/fisher/fisher.bundle.js, Line: 13376)"

**Comment by stinkpalmd** [comment] 2022-01-08 17:14
I noticed this too. The funny thing is if you mooch a fish, the layout somehow shows and isn't frozen/hidden. It's very odd. Hoping this gets fixed because the overlay would be super helpful to know a Horizon Event tug!

**Comment by NolanSeryn** [comment] 2022-01-09 00:17
>The funny thing is if you mooch a fish, the layout somehow shows and isn't frozen/hidden.

I'm guessing the mooch circumvents this, because you're just "Casting with the fish still attached" as far as the Fisher plugin is concerned - rather than casting your line at the 'forbidden spots'.

**Comment by quisquous** [comment] 2022-01-10 17:30
Sorry, it will be a good while before I have any time to look at this.  If you can figure out what's wrong, I'd be happy to look at a PR.

**Comment by valarnin** [comment] 2022-04-11 11:19
From the 6.1 patch notes:
> An issue in Ultima Thule wherein using the fisher action Cast at fishing holes under certain conditions displayed the name of the wrong fishing hole.

Possibly related?

**Comment by rocketmantis** [comment] 2022-05-07 02:18
The problem is \w apparently doesn't include Greek letters.

```
(fisher.js, line 85)
        'cast': /00:08c3:(?:[\w']\.?)(?:[\w'\s]+\.?)? cast(?:s?) (?:your|his|her) line (?:on|in|at) (?:the )?([\w\s'&()]+)\./,
```

Changing this in the bundled version fixes the problem with these holes (tested on apohelos 18-β):
```
(fisher.bundle.js, line 13787)
--          line: '(?:[\\w\']\\.?)(?:[\\w\'\\s]+\\.?)? cast(?:s?) (?:your|his|her) line (?:on|in|at) (?:the )?(?<place>[\\w\\s\'&()]+)\\..*?'
++          line: '(?:[\\w\']\\.?)(?:[\\w\'\\s]+\\.?)? cast(?:s?) (?:your|his|her) line (?:on|in|at) (?:the )?(?<place>.+)\\..*?'
```

Using . instead of \w\s etc feels more reliable to me than trying to catch all the specific variant characters they might use in the future. I guess you could try including U+0391 - U+03C9 directly to catch all the Greek letters, but who knows if they'll start putting Cyrillic in fishing hole names in the future or something.

Presumably you will also want to update the regex in other places too, most notably the EN 'discovered' pattern, and at least check the cast and discovered strings for the other languages as well. But switching to .+ does fix the issue for me in EN at least as a workaround for now.

**Comment by MyTechnoHunter** [comment] 2022-05-08 18:50
@rocketmantis can you make a PR for your fix? seems like it should work and will let it get merged :)

**Closed** 2022-06-28 05:02 UTC
Labels: bug, help wanted, fishing🎣
