### ISSUE TITLE
Fisher Overlay not recording mooches

### ISSUE THREAD

**Issue by majesticuni** [quisquous/cactbot#425] opened 2019-06-18 16:24 UTC
Whenever you mooch a fish the overlay doesnt keep track of what was caught with mooches and the timer ends etc

**Comment by majesticuni** [comment] 2019-06-18 16:26
easy example is go to mor dhona and try to fish up a ninja betta and the assassin betta fish doesnt show up when u mooch a ala mhgian fighting fish

**Comment by quisquous** [comment] 2019-06-22 22:05
I think this is a duplicate of #363, so I'm going to close this one.

**Closed by quisquous** 2019-06-22 22:05 UTC
Labels: duplicate
